// ═══════════════════════════════════════════════════════════════════════
// Agent 工厂 — 从 DSL 配置生成可运行的 Agent 代码
// Agent Factory — generates runnable Agent code from DSL config
// ═══════════════════════════════════════════════════════════════════════

import type { AgentDSLConfig, PersonalityConfig, BehaviorConfig, ToolConfig, ExtensionConfig } from "@/lib/agent-dsl";
import type { Agent } from "@/data/agents";

/** 工厂输出 / Factory output */
export interface AgentFactoryOutput {
  /** Agent 入口定义（可插入 agents.ts）/ Agent entry definition (can be inserted into agents.ts) */
  agentEntry: string;
  /** 系统提示词 / System prompt */
  systemPrompt: string;
  /** 工具定义 JSON / Tool definitions JSON */
  toolDefinitions: string;
  /** 完整代码包 / Complete code package */
  fullCode: string;
}

/** 从 DSL 配置生成 Agent 入口 / Generate Agent entry from DSL config */
export function generateAgentEntry(config: AgentDSLConfig): string {
  return `  {
    name: "${config.name}",
    emoji: "${config.emoji}",
    role: "${config.role}",
    category: "${config.category}",
    personality: "${config.personality.type}",
    description: "${config.description}",
    isCreator: false,
  },`;
}

/** 从 DSL 配置生成系统提示词 / Generate system prompt from DSL config */
export function generateSystemPrompt(config: AgentDSLConfig): string {
  const p = config.personality;
  const b = config.behavior;

  const lines = [
    `# ${config.name} — ${config.role}`,
    "",
    `## 身份`,
    `你是 ${config.name}，${config.description}`,
    "",
    `## 性格参数`,
    `- 类型：${p.type}（细节程度：${p.detail_level}，风险容忍度：${p.risk_tolerance}）`,
    `- 辩论风格：${p.debate_style}`,
    `- 创造力：${p.creativity}，啰嗦程度：${p.verbosity}`,
    `- 共情：${p.empathy}，自信：${p.confidence}`,
    "",
    `## 能力领域`,
    ...config.capabilities.map((c) => `- ${c}`),
    "",
    `## 知识领域`,
    ...config.knowledge.map((k) => `- ${k}`),
    "",
    `## 行为规则`,
    `- 遇到错误时：${b.on_error}`,
    `- 遇到冲突时：${b.on_conflict}`,
    `- 不确定时：${b.on_uncertain}`,
    `- 最大重试次数：${b.max_retries}`,
    `- 回复格式：${b.response_format}`,
    "",
    `## 约束`,
    ...config.constraints.map((c) => `- ${c}`),
    "",
    `## 触发条件`,
    ...config.triggers.map((t) => `- ${t}`),
    "",
    `## 协作规则`,
    `1. 以你的专业领域为核心，提供具体、可操作的建议`,
    `2. 使用工具时，遵守工具配置中的权限限制`,
    `3. 与其他 Agent 协作时，遵循你的辩论风格和冲突处理规则`,
    `4. 不确定时，根据行为规则决定是猜测还是请求澄清`,
    `5. 始终在你的约束条件下工作`,
  ];

  return lines.join("\n");
}

/** 从工具配置生成 OpenAI 工具定义 JSON / Generate OpenAI tool definitions from tool config */
export function generateToolDefinitions(tools: ToolConfig[]): string {
  if (tools.length === 0) return "[]";

  const definitions = tools.map((t) => {
    const props: Record<string, unknown> = {};
    for (const [k, v] of Object.entries(t.config)) {
      if (k === "formats" && Array.isArray(v)) {
        props.format = { type: "string", enum: v, description: "输出格式" };
      } else if (k === "allowed_paths") {
        props.path = { type: "string", description: `允许的路径：${Array.isArray(v) ? v.join(", ") : v}` };
      } else if (k === "allowed_commands") {
        props.command = { type: "string", description: `允许的命令：${Array.isArray(v) ? v.join(", ") : v}` };
      } else if (k === "max_file_size") {
        props.max_size = { type: "string", description: `最大文件大小：${v}` };
      } else if (k === "timeout") {
        props.timeout = { type: "number", description: `超时时间（秒）：${v}` };
      }
    }

    return {
      type: "function",
      function: {
        name: t.name,
        description: `${t.type} 工具 — 配置：${JSON.stringify(t.config)}`,
        parameters: {
          type: "object",
          properties: props,
          required: Object.keys(props),
        },
      },
    };
  });

  return JSON.stringify(definitions, null, 2);
}

/** 从 DSL 配置生成完整的 Agent 代码包 / Generate complete agent code package from DSL config */
export function generateAgentPackage(config: AgentDSLConfig): AgentFactoryOutput {
  return {
    agentEntry: generateAgentEntry(config),
    systemPrompt: generateSystemPrompt(config),
    toolDefinitions: generateToolDefinitions(config.tools),
    fullCode: generateFullCode(config),
  };
}

/** 生成完整代码包 / Generate full code package */
function generateFullCode(config: AgentDSLConfig): string {
  const lines = [
    `// ═════════════════════════════════════════════════════════════════`,
    `// Agent: ${config.name}`,
    `// Role: ${config.role}`,
    `// Category: ${config.category}`,
    `// Generated by OmniMind Nexus Creator`,
    `// ═════════════════════════════════════════════════════════════════`,
    "",
    `import type { Agent } from "@/data/agents";`,
    "",
    `// ── Agent 定义 / Agent Definition ──`,
    `export const ${toCamelCase(config.name)}Agent: Agent = {`,
    `  name: "${config.name}",`,
    `  emoji: "${config.emoji}",`,
    `  role: "${config.role}",`,
    `  category: "${config.category}",`,
    `  personality: "${config.personality.type}",`,
    `  description: "${config.description}",`,
    `  isCreator: false,`,
    `};`,
    "",
    `// ── 系统提示词 / System Prompt ──`,
    `export const ${toCamelCase(config.name)}Prompt = \`${generateSystemPrompt(config)}\`;`,
    "",
    `// ── 工具定义 / Tool Definitions ──`,
    `export const ${toCamelCase(config.name)}Tools = ${generateToolDefinitions(config.tools)};`,
    "",
    `// ── 行为配置 / Behavior Config ──`,
    `export const ${toCamelCase(config.name)}Behavior = ${JSON.stringify(config.behavior, null, 2)};`,
    "",
    `// ── 触发条件 / Triggers ──`,
    `export const ${toCamelCase(config.name)}Triggers = ${JSON.stringify(config.triggers, null, 2)};`,
  ];

  return lines.join("\n");
}

/** 转驼峰命名 / Convert to camelCase */
function toCamelCase(name: string): string {
  return name
    .replace(/[^a-zA-Z0-9\s]/g, "")
    .split(/\s+/)
    .map((w, i) => i === 0 ? w.toLowerCase() : w.charAt(0).toUpperCase() + w.slice(1).toLowerCase())
    .join("");
}

/** 批量生成多个 Agent 的入口代码 / Batch generate agent entries for multiple agents */
export function generateAgentRegistry(configs: AgentDSLConfig[]): string {
  const lines = [
    "// ═════════════════════════════════════════════════════════════════",
    "// Auto-generated Agent Registry",
    "// Generated by OmniMind Nexus Creator",
    "// ═════════════════════════════════════════════════════════════════",
    "",
    "import type { Agent } from \"@/data/agents\";",
    "",
    "export const customAgents: Agent[] = [",
  ];

  for (const config of configs) {
    lines.push(`  {`);
    lines.push(`    name: "${config.name}",`);
    lines.push(`    emoji: "${config.emoji}",`);
    lines.push(`    role: "${config.role}",`);
    lines.push(`    category: "${config.category}",`);
    lines.push(`    personality: "${config.personality.type}",`);
    lines.push(`    description: "${config.description}",`);
    lines.push(`    isCreator: false,`);
    lines.push(`  },`);
  }

  lines.push("];");
  return lines.join("\n");
}