// ═══════════════════════════════════════════════════════════════════════
// Agent 工厂 — 从 DSL 配置生成可运行的 Agent 代码
// Agent Factory — generates runnable Agent code from DSL config
// ═══════════════════════════════════════════════════════════════════════

import type { AgentDSLConfig, PersonalityConfig, BehaviorConfig, ToolConfig, ExtensionConfig, EventHook, PipelineConfig, PipelineStep, StateMachineConfig, CommunicationConfig, MemoryConfig, SwarmDSLConfig, EvolutionDSLConfig, KnowledgeGraphDSLConfig, MetacognitionDSLConfig } from "@/lib/agent-dsl";
import type { Agent } from "@/data/agents";

/** 工厂输出 / Factory output */
export interface AgentFactoryOutput {
  /** Agent 入口定义（可插入 agents.ts）/ Agent entry definition (can be inserted into agents.ts) */
  agentEntry: string;
  /** 系统提示词 / System prompt */
  systemPrompt: string;
  /** 工具定义 JSON / Tool definitions JSON */
  toolDefinitions: string;
  /** 完整代码包 / Complete code package */
  fullCode: string;
}

/** 从 DSL 配置生成 Agent 入口 / Generate Agent entry from DSL config */
export function generateAgentEntry(config: AgentDSLConfig): string {
  return `  {
    name: "${config.name}",
    emoji: "${config.emoji}",
    role: "${config.role}",
    category: "${config.category}",
    personality: "${config.personality.type}",
    description: "${config.description}",
    isCreator: false,
  },`;
}

/** 从 DSL 配置生成系统提示词 / Generate system prompt from DSL config */
export function generateSystemPrompt(config: AgentDSLConfig): string {
  const p = config.personality;
  const b = config.behavior;

  const lines = [
    `# ${config.name} — ${config.role}`,
    "",
    `## 身份`,
    `你是 ${config.name}，${config.description}`,
    "",
    `## 性格参数`,
    `- 类型：${p.type}（细节程度：${p.detail_level}，风险容忍度：${p.risk_tolerance}）`,
    `- 辩论风格：${p.debate_style}`,
    `- 创造力：${p.creativity}，啰嗦程度：${p.verbosity}`,
    `- 共情：${p.empathy}，自信：${p.confidence}`,
    "",
    `## 能力领域`,
    ...config.capabilities.map((c) => `- ${c}`),
    "",
    `## 知识领域`,
    ...config.knowledge.map((k) => `- ${k}`),
    "",
    `## 行为规则`,
    `- 遇到错误时：${b.on_error}`,
    `- 遇到冲突时：${b.on_conflict}`,
    `- 不确定时：${b.on_uncertain}`,
    `- 最大重试次数：${b.max_retries}`,
    `- 回复格式：${b.response_format}`,
    "",
    `## 约束`,
    ...config.constraints.map((c) => `- ${c}`),
    "",
    `## 触发条件`,
    ...config.triggers.map((t) => `- ${t}`),
    "",
    `## 协作规则`,
    `1. 以你的专业领域为核心，提供具体、可操作的建议`,
    `2. 使用工具时，遵守工具配置中的权限限制`,
    `3. 与其他 Agent 协作时，遵循你的辩论风格和冲突处理规则`,
    `4. 不确定时，根据行为规则决定是猜测还是请求澄清`,
    `5. 始终在你的约束条件下工作`,
  ];

  return lines.join("\n");
}

/** 从工具配置生成 OpenAI 工具定义 JSON / Generate OpenAI tool definitions from tool config */
export function generateToolDefinitions(tools: ToolConfig[]): string {
  if (tools.length === 0) return "[]";

  const definitions = tools.map((t) => {
    const props: Record<string, unknown> = {};
    for (const [k, v] of Object.entries(t.config)) {
      if (k === "formats" && Array.isArray(v)) {
        props.format = { type: "string", enum: v, description: "输出格式" };
      } else if (k === "allowed_paths") {
        props.path = { type: "string", description: `允许的路径：${Array.isArray(v) ? v.join(", ") : v}` };
      } else if (k === "allowed_commands") {
        props.command = { type: "string", description: `允许的命令：${Array.isArray(v) ? v.join(", ") : v}` };
      } else if (k === "max_file_size") {
        props.max_size = { type: "string", description: `最大文件大小：${v}` };
      } else if (k === "timeout") {
        props.timeout = { type: "number", description: `超时时间（秒）：${v}` };
      }
    }

    return {
      type: "function",
      function: {
        name: t.name,
        description: `${t.type} 工具 — 配置：${JSON.stringify(t.config)}`,
        parameters: {
          type: "object",
          properties: props,
          required: Object.keys(props),
        },
      },
    };
  });

  return JSON.stringify(definitions, null, 2);
}

/** 从 DSL 配置生成完整的 Agent 代码包 / Generate complete agent code package from DSL config */
export function generateAgentPackage(config: AgentDSLConfig): AgentFactoryOutput {
  return {
    agentEntry: generateAgentEntry(config),
    systemPrompt: generateSystemPrompt(config),
    toolDefinitions: generateToolDefinitions(config.tools),
    fullCode: generateFullCode(config),
  };
}

/** 生成完整代码包 / Generate full code package */
function generateFullCode(config: AgentDSLConfig): string {
  const lines = [
    `// ═════════════════════════════════════════════════════════════════`,
    `// Agent: ${config.name}`,
    `// Role: ${config.role}`,
    `// Category: ${config.category}`,
    `// Generated by OmniMind Nexus Creator`,
    `// ═════════════════════════════════════════════════════════════════`,
    "",
    `import type { Agent } from "@/data/agents";`,
    "",
    `// ── Agent 定义 / Agent Definition ──`,
    `export const ${toCamelCase(config.name)}Agent: Agent = {`,
    `  name: "${config.name}",`,
    `  emoji: "${config.emoji}",`,
    `  role: "${config.role}",`,
    `  category: "${config.category}",`,
    `  personality: "${config.personality.type}",`,
    `  description: "${config.description}",`,
    `  isCreator: false,`,
    `};`,
    "",
    `// ── 系统提示词 / System Prompt ──`,
    `export const ${toCamelCase(config.name)}Prompt = \`${generateSystemPrompt(config)}\`;`,
    "",
    `// ── 工具定义 / Tool Definitions ──`,
    `export const ${toCamelCase(config.name)}Tools = ${generateToolDefinitions(config.tools)};`,
    "",
    `// ── 行为配置 / Behavior Config ──`,
    `export const ${toCamelCase(config.name)}Behavior = ${JSON.stringify(config.behavior, null, 2)};`,
    "",
    `// ── 触发条件 / Triggers ──`,
    `export const ${toCamelCase(config.name)}Triggers = ${JSON.stringify(config.triggers, null, 2)};`,
  ];

  // 事件钩子 / Event hooks
  if (config.events && config.events.length > 0) {
    lines.push("");
    lines.push(`// ── 事件钩子 / Event Hooks ──`);
    lines.push(`export const ${toCamelCase(config.name)}Events = ${generateEventsCode(config.events)};`);
  }

  // 变量 / Variables
  if (config.variables && Object.keys(config.variables).length > 0) {
    lines.push("");
    lines.push(`// ── 变量定义 / Variable Definitions ──`);
    lines.push(`export const ${toCamelCase(config.name)}Variables = ${JSON.stringify(config.variables, null, 2)};`);
  }

  // 管道 / Pipelines
  if (config.pipelines && config.pipelines.length > 0) {
    lines.push("");
    lines.push(`// ── 管道定义 / Pipeline Definitions ──`);
    lines.push(`export const ${toCamelCase(config.name)}Pipelines = ${generatePipelinesCode(config.pipelines)};`);
  }

  // 状态机 / State machine
  if (config.state_machine) {
    lines.push("");
    lines.push(`// ── 状态机 / State Machine ──`);
    lines.push(`export const ${toCamelCase(config.name)}StateMachine = ${generateStateMachineCode(config.state_machine)};`);
  }

  // 通信 / Communication
  if (config.communication) {
    lines.push("");
    lines.push(`// ── 通信配置 / Communication Config ──`);
    lines.push(`export const ${toCamelCase(config.name)}Communication = ${generateCommunicationCode(config.communication)};`);
  }

  // 内存 / Memory
  if (config.memory) {
    lines.push("");
    lines.push(`// ── 内存配置 / Memory Config ──`);
    lines.push(`export const ${toCamelCase(config.name)}Memory = ${generateMemoryCode(config.memory)};`);
  }

  // 蜂群智能 / Swarm intelligence
  if (config.swarm) {
    lines.push("");
    lines.push(`// ── 蜂群智能配置 / Swarm Intelligence Config ──`);
    lines.push(`export const ${toCamelCase(config.name)}Swarm = ${generateSwarmCode(config.swarm)};`);
    lines.push("");
    lines.push(`// 蜂群共识运行器 / Swarm consensus runner`);
    lines.push(`import { runSwarmConsensus, createSwarmMemory } from "@/lib/swarm";`);
    lines.push(`export async function run${toPascalCase(config.name)}Swarm(`);
    lines.push(`  agentNames: string[],`);
    lines.push(`  fitnessFn: (pos: number[]) => number`);
    lines.push(`) {`);
    lines.push(`  const memory = createSwarmMemory(${config.swarm.dimensions});`);
    lines.push(`  return runSwarmConsensus(`);
    lines.push(`    {`);
    lines.push(`      populationSize: ${config.swarm.population_size},`);
    lines.push(`      maxIterations: ${config.swarm.max_iterations},`);
    lines.push(`      convergenceThreshold: ${config.swarm.convergence_threshold},`);
    lines.push(`      explorationRatio: ${config.swarm.exploration_ratio},`);
    lines.push(`      pheromoneWeight: ${config.swarm.pheromone_weight},`);
    lines.push(`      socialWeight: ${config.swarm.social_weight},`);
    lines.push(`      cognitiveWeight: ${config.swarm.cognitive_weight},`);
    lines.push(`      inertiaWeight: ${config.swarm.inertia_weight},`);
    lines.push(`      dimensions: ${config.swarm.dimensions},`);
    lines.push(`      bounds: [${config.swarm.bounds[0]}, ${config.swarm.bounds[1]}],`);
    lines.push(`    },`);
    lines.push(`    agentNames,`);
    lines.push(`    fitnessFn,`);
    lines.push(`  );`);
    lines.push(`}`);
  }

  // 进化引擎 / Evolution engine
  if (config.evolution) {
    lines.push("");
    lines.push(`// ── 进化引擎配置 / Evolution Engine Config ──`);
    lines.push(`export const ${toCamelCase(config.name)}Evolution = ${generateEvolutionCode(config.evolution)};`);
    lines.push("");
    lines.push(`// 进化运行器 / Evolution runner`);
    lines.push(`import { runEvolution, initializePopulation } from "@/lib/evolution";`);
    lines.push(`export async function evolve${toPascalCase(config.name)}Parameters(`);
    lines.push(`  fitnessFn: (chromosome: import("@/lib/evolution").Chromosome) => Promise<number>`);
    lines.push(`) {`);
    lines.push(`  return runEvolution(`);
    lines.push(`    {`);
    lines.push(`      populationSize: ${config.evolution.population_size},`);
    lines.push(`      eliteCount: ${config.evolution.elite_count},`);
    lines.push(`      crossoverRate: ${config.evolution.crossover_rate},`);
    lines.push(`      mutationRate: ${config.evolution.mutation_rate},`);
    lines.push(`      tournamentSize: ${config.evolution.tournament_size},`);
    lines.push(`      maxGenerations: ${config.evolution.max_generations},`);
    lines.push(`      targetFitness: ${config.evolution.target_fitness},`);
    lines.push(`      stagnationLimit: ${config.evolution.stagnation_limit},`);
    lines.push(`    },`);
    lines.push(`    fitnessFn,`);
    lines.push(`  );`);
    lines.push(`}`);
  }

  // 知识图谱 / Knowledge graph
  if (config.knowledge_graph) {
    lines.push("");
    lines.push(`// ── 知识图谱配置 / Knowledge Graph Config ──`);
    lines.push(`export const ${toCamelCase(config.name)}KnowledgeGraph = ${generateKnowledgeGraphCode(config.knowledge_graph)};`);
    lines.push("");
    lines.push(`// 知识图谱查询器 / Knowledge graph query helpers`);
    lines.push(`import { createKnowledgeGraph, addEntity, addRelation, queryGraph, findPath } from "@/lib/knowledge-graph";`);
    lines.push(`export const ${toCamelCase(config.name)}Graph = createKnowledgeGraph();`);
    lines.push(`export function query${toPascalCase(config.name)}Knowledge(startEntity: string, maxDepth = 3) {`);
    lines.push(`  return queryGraph(${toCamelCase(config.name)}Graph, {`);
    lines.push(`    startEntity,`);
    lines.push(`    maxDepth,`);
    lines.push(`    minConfidence: ${config.knowledge_graph.confidence_threshold},`);
    lines.push(`    minWeight: 0.1,`);
    lines.push(`    limit: 20,`);
    lines.push(`  });`);
    lines.push(`}`);
  }

  // 元认知 / Metacognition
  if (config.metacognition) {
    lines.push("");
    lines.push(`// ── 元认知配置 / Metacognition Config ──`);
    lines.push(`export const ${toCamelCase(config.name)}Metacognition = ${generateMetacognitionCode(config.metacognition)};`);
    lines.push("");
    lines.push(`// 元认知管理器 / Metacognition manager`);
    lines.push(`import { createMetacognitionManager, startThinking, recordThinking, endThinking } from "@/lib/metacognition";`);
    lines.push(`export const ${toCamelCase(config.name)}Meta = createMetacognitionManager({`);
    lines.push(`  enabled: ${config.metacognition.enabled},`);
    lines.push(`  trackThinking: ${config.metacognition.track_thinking},`);
    lines.push(`  detectBiases: ${config.metacognition.detect_biases},`);
    lines.push(`  calibrateConfidence: ${config.metacognition.calibrate_confidence},`);
    lines.push(`  autoReflect: ${config.metacognition.auto_reflect},`);
    lines.push(`  reflectInterval: ${config.metacognition.reflect_interval},`);
    lines.push(`  minConfidenceForAction: ${config.metacognition.min_confidence},`);
    lines.push(`  biasSeverityThreshold: ${config.metacognition.bias_severity_threshold},`);
    lines.push(`  maxThinkingChainLength: ${config.metacognition.max_thinking_steps},`);
    lines.push(`});`);
  }

  return lines.join("\n");
}

/** 生成事件钩子代码 / Generate event hooks code */
function generateEventsCode(events: EventHook[]): string {
  const lines: string[] = [];
  lines.push(`// Event hooks for the agent`);
  lines.push(`// Triggered at specific lifecycle points`);
  for (const ev of events) {
    lines.push(`// ${ev.event}: ${ev.action}${ev.condition ? ` (if ${ev.condition})` : ""} [async=${ev.async}, priority=${ev.priority}]`);
  }
  return JSON.stringify(events, null, 2);
}

/** 生成管道代码 / Generate pipelines code */
function generatePipelinesCode(pipelines: PipelineConfig[]): string {
  return JSON.stringify(pipelines, null, 2);
}

/** 生成状态机代码 / Generate state machine code */
function generateStateMachineCode(sm: StateMachineConfig): string {
  return JSON.stringify(sm, null, 2);
}

/** 生成通信配置代码 / Generate communication config code */
function generateCommunicationCode(comm: CommunicationConfig): string {
  return JSON.stringify(comm, null, 2);
}

/** 生成内存配置代码 / Generate memory config code */
function generateMemoryCode(mem: MemoryConfig): string {
  return JSON.stringify(mem, null, 2);
}

/** 生成蜂群配置代码 / Generate swarm config code */
function generateSwarmCode(swarm: SwarmDSLConfig): string {
  return JSON.stringify(swarm, null, 2);
}

/** 生成进化配置代码 / Generate evolution config code */
function generateEvolutionCode(evol: EvolutionDSLConfig): string {
  return JSON.stringify(evol, null, 2);
}

/** 生成知识图谱配置代码 / Generate knowledge graph config code */
function generateKnowledgeGraphCode(kg: KnowledgeGraphDSLConfig): string {
  return JSON.stringify(kg, null, 2);
}

/** 生成元认知配置代码 / Generate metacognition config code */
function generateMetacognitionCode(meta: MetacognitionDSLConfig): string {
  return JSON.stringify(meta, null, 2);
}

/** 转驼峰命名 / Convert to camelCase */
function toCamelCase(name: string): string {
  return name
    .replace(/[^a-zA-Z0-9\s]/g, "")
    .split(/\s+/)
    .map((w, i) => i === 0 ? w.toLowerCase() : w.charAt(0).toUpperCase() + w.slice(1).toLowerCase())
    .join("");
}

/** 转帕斯卡命名 / Convert to PascalCase */
function toPascalCase(name: string): string {
  return name
    .replace(/[^a-zA-Z0-9\s]/g, "")
    .split(/\s+/)
    .map((w) => w.charAt(0).toUpperCase() + w.slice(1).toLowerCase())
    .join("");
}

/** 批量生成多个 Agent 的入口代码 / Batch generate agent entries for multiple agents */
export function generateAgentRegistry(configs: AgentDSLConfig[]): string {
  const lines = [
    "// ═════════════════════════════════════════════════════════════════",
    "// Auto-generated Agent Registry",
    "// Generated by OmniMind Nexus Creator",
    "// ═════════════════════════════════════════════════════════════════",
    "",
    "import type { Agent } from \"@/data/agents\";",
    "",
    "export const customAgents: Agent[] = [",
  ];

  for (const config of configs) {
    lines.push(`  {`);
    lines.push(`    name: "${config.name}",`);
    lines.push(`    emoji: "${config.emoji}",`);
    lines.push(`    role: "${config.role}",`);
    lines.push(`    category: "${config.category}",`);
    lines.push(`    personality: "${config.personality.type}",`);
    lines.push(`    description: "${config.description}",`);
    lines.push(`    isCreator: false,`);
    lines.push(`  },`);
  }

  lines.push("];");
  return lines.join("\n");
}