// ═══════════════════════════════════════════════════════════════════════
// Next.js 代码生成器 — 从 DSL 扩展配置生成 Next.js 代码
// Next.js Code Builder — generates Next.js code from DSL extension config
// ═══════════════════════════════════════════════════════════════════════

import type { APIRouteConfig, ComponentConfig, ExtensionConfig, AgentDSLConfig } from "@/lib/agent-dsl";

/** 生成的 API 路由 / Generated API route */
export interface GeneratedRoute {
  fileName: string;
  filePath: string;
  code: string;
  description: string;
}

/** 生成的组件 / Generated component */
export interface GeneratedComponent {
  fileName: string;
  filePath: string;
  code: string;
  description: string;
}

/** 完整的 Next.js 扩展包 / Complete Next.js extension package */
export interface NextJsExtension {
  routes: GeneratedRoute[];
  components: GeneratedComponent[];
  readme: string;
}

/** 生成 API 路由代码 / Generate API route code */
export function generateAPIRoute(route: APIRouteConfig, agentName: string): GeneratedRoute {
  const method = route.method.toUpperCase();
  const routePath = route.path.startsWith("/") ? route.path : `/${route.path}`;
  const fileName = routePath.replace(/\//g, "_").replace(/^_/, "") + ".ts";
  const filePath = `src/app/api${routePath}/route.ts`;

  const paramsDestructure = route.params
    ? `const { ${Object.keys(route.params).join(", ")} } = await request.json();`
    : "";

  const paramsValidation = route.params
    ? Object.entries(route.params)
        .map(([k, v]) => `    if (!${k}) return NextResponse.json({ error: "${v} is required" }, { status: 400 });`)
        .join("\n")
    : "";

  const code = `// ═════════════════════════════════════════════════════════════════
// ${route.description}
// Agent: ${agentName}
// Generated by OmniMind Nexus Creator
// ═════════════════════════════════════════════════════════════════

import { NextRequest, NextResponse } from "next/server";
${route.auth_required ? 'import { getServerSession } from "next-auth";' : ""}

export async function ${method}${method === "GET" ? "(request: NextRequest)" : "(request: NextRequest)"} {
  try {
    ${route.auth_required ? `
    // 认证检查 / Auth check
    const session = await getServerSession();
    if (!session) {
      return NextResponse.json({ error: "Unauthorized" }, { status: 401 });
    }
    ` : ""}
    // 解析请求参数 / Parse request params
    ${paramsDestructure}
    ${paramsValidation}

    // TODO: 在此实现 Agent 处理逻辑 / Implement agent processing logic here
    // 调用 LLM 或执行工具 / Call LLM or execute tools

    return NextResponse.json({
      success: true,
      agent: "${agentName}",
      message: "处理完成",
      timestamp: new Date().toISOString(),
    });

  } catch (error) {
    console.error("[${agentName}] API Error:", error);
    return NextResponse.json(
      { error: "Internal server error", details: String(error) },
      { status: 500 }
    );
  }
}`;

  return { fileName, filePath, code, description: route.description };
}

/** 生成 React 组件代码 / Generate React component code */
export function generateComponent(comp: ComponentConfig, agentName: string): GeneratedComponent {
  const fileName = `${comp.name}.tsx`;
  const filePath = `src/components/${comp.name}.tsx`;

  const propsInterface = comp.props
    .map((p) => `  ${p}: string;`)
    .join("\n");

  const isClient = comp.type === "client";

  const code = `// ═════════════════════════════════════════════════════════════════
// ${comp.name} — ${comp.description || `${agentName} 专用组件`}
// Agent: ${agentName}
// Generated by OmniMind Nexus Creator
// ═════════════════════════════════════════════════════════════════
${isClient ? '"use client";\n' : ""}
import { motion } from "framer-motion";

interface ${comp.name}Props {
${propsInterface}
}

export default function ${comp.name}({ ${comp.props.join(", ")} }: ${comp.name}Props) {
  return (
    <motion.div
      initial={{ opacity: 0, y: 12 }}
      animate={{ opacity: 1, y: 0 }}
      transition={{ duration: 0.4 }}
      className="border-2 border-ink bg-white p-4"
    >
      <div className="flex items-center gap-2 mb-3">
        <span className="pixel-text text-[10px] tracking-[0.15em] text-ink/50 uppercase">
          {comp.name}
        </span>
      </div>
      <div className="space-y-2">
        ${comp.props.map((p) => `
        <div className="flex items-center gap-2">
          <span className="pixel-text text-[9px] text-ink/40 w-16">{p}:</span>
          <span className="pixel-text text-[11px] text-ink/80">{${p}}</span>
        </div>`).join("")}
      </div>
    </motion.div>
  );
}`;

  return { fileName, filePath, code, description: comp.description || `${comp.name} 组件` };
}

/** 从扩展配置生成完整的 Next.js 扩展包 / Generate complete Next.js extension package from extension config */
export function generateNextJsExtension(ext: ExtensionConfig, agentName: string): NextJsExtension {
  const routes = ext.api_routes.map((r) => generateAPIRoute(r, agentName));
  const components = ext.components.map((c) => generateComponent(c, agentName));

  const readme = `# ${agentName} — Next.js Extension

## API Routes
${routes.map((r) => `- **${r.filePath}** — ${r.description}`).join("\n")}

## Components
${components.map((c) => `- **${c.filePath}** — ${c.description}`).join("\n")}

## 使用方式 / Usage

### 安装依赖
\`\`\`bash
npm install
\`\`\`

### 导入组件
\`\`\`tsx
${components.map((c) => `import ${c.filePath.split("/").pop()?.replace(".tsx", "")} from "${c.filePath.replace("src/", "@/").replace(".tsx", "")}";`).join("\n")}
\`\`\`

### 调用 API
\`\`\`ts
${routes.map((r) => `// ${r.description}
const res = await fetch("${r.filePath.replace("src/app", "").replace("/route.ts", "")}", {
  method: "${r.filePath.includes("GET") ? "GET" : "POST"}",
  headers: { "Content-Type": "application/json" },
  body: JSON.stringify({ /* params */ }),
});`).join("\n\n")}
\`\`\`

---
Generated by OmniMind Nexus Creator
`;

  return { routes, components, readme };
}

/** 从完整的 Agent DSL 配置生成所有扩展代码 / Generate all extension code from full Agent DSL config */
export function generateFullExtension(config: AgentDSLConfig): NextJsExtension {
  return generateNextJsExtension(config.extension, config.name);
}

/** 生成自定义功能的 Next.js 代码（自由形式）/ Generate custom Next.js code (free-form) */
export function buildCustomNextJsCode(
  featureName: string,
  description: string,
  codeType: "api" | "component" | "page" | "layout" | "middleware",
  implementation: string,
): string {
  const header = `// ═════════════════════════════════════════════════════════════════
// ${featureName}
// ${description}
// Generated by OmniMind Nexus Creator
// ═════════════════════════════════════════════════════════════════
`;

  const boilerplate = getBoilerplate(codeType, featureName);

  return header + boilerplate.replace("// TODO: implementation", implementation);
}

/** 获取代码模板 / Get code boilerplate */
function getBoilerplate(type: string, name: string): string {
  switch (type) {
    case "api":
      return `
import { NextRequest, NextResponse } from "next/server";

export async function POST(request: NextRequest) {
  try {
    const body = await request.json();
    // TODO: implementation
    return NextResponse.json({ success: true });
  } catch (error) {
    return NextResponse.json({ error: String(error) }, { status: 500 });
  }
}
`;
    case "component":
      return `
"use client";

import { motion } from "framer-motion";

interface ${name}Props {
  data?: unknown;
}

export default function ${name}({ data }: ${name}Props) {
  return (
    <motion.div
      initial={{ opacity: 0 }}
      animate={{ opacity: 1 }}
      className="border-2 border-ink bg-white p-4"
    >
      // TODO: implementation
    </motion.div>
  );
}
`;
    case "page":
      return `
import { Metadata } from "next";

export const metadata: Metadata = {
  title: "${name}",
  description: "Generated by OmniMind Nexus Creator",
};

export default function ${name}Page() {
  return (
    <main className="min-h-screen bg-white p-8">
      // TODO: implementation
    </main>
  );
}
`;
    case "layout":
      return `
import { ReactNode } from "react";

export default function ${name}Layout({ children }: { children: ReactNode }) {
  return (
    <div className="min-h-screen bg-white">
      // TODO: implementation
      {children}
    </div>
  );
}
`;
    case "middleware":
      return `
import { NextRequest, NextResponse } from "next/server";

export function middleware(request: NextRequest) {
  // TODO: implementation
  return NextResponse.next();
}

export const config = {
  matcher: ["/api/:path*"],
};
`;
    default:
      return "// TODO: implementation";
  }
}