// ═══════════════════════════════════════════════════════════════════════
// Next.js 代码生成器 — 从 DSL 扩展配置生成 Next.js 代码
// Next.js Code Builder — generates Next.js code from DSL extension config
// ═══════════════════════════════════════════════════════════════════════

import type { APIRouteConfig, ComponentConfig, ExtensionConfig, AgentDSLConfig, EventHook, PipelineConfig, StateMachineConfig, CommunicationConfig } from "@/lib/agent-dsl";

/** 生成的 API 路由 / Generated API route */
export interface GeneratedRoute {
  fileName: string;
  filePath: string;
  code: string;
  description: string;
}

/** 生成的组件 / Generated component */
export interface GeneratedComponent {
  fileName: string;
  filePath: string;
  code: string;
  description: string;
}

/** 完整的 Next.js 扩展包 / Complete Next.js extension package */
export interface NextJsExtension {
  routes: GeneratedRoute[];
  components: GeneratedComponent[];
  readme: string;
}

/** 生成 API 路由代码 / Generate API route code */
export function generateAPIRoute(route: APIRouteConfig, agentName: string): GeneratedRoute {
  const method = route.method.toUpperCase();
  const routePath = route.path.startsWith("/") ? route.path : `/${route.path}`;
  const fileName = routePath.replace(/\//g, "_").replace(/^_/, "") + ".ts";
  const filePath = `src/app/api${routePath}/route.ts`;

  const paramsDestructure = route.params
    ? `const { ${Object.keys(route.params).join(", ")} } = await request.json();`
    : "";

  const paramsValidation = route.params
    ? Object.entries(route.params)
        .map(([k, v]) => `    if (!${k}) return NextResponse.json({ error: "${v} is required" }, { status: 400 });`)
        .join("\n")
    : "";

  const code = `// ═════════════════════════════════════════════════════════════════
// ${route.description}
// Agent: ${agentName}
// Generated by OmniMind Nexus Creator
// ═════════════════════════════════════════════════════════════════

import { NextRequest, NextResponse } from "next/server";
${route.auth_required ? 'import { getServerSession } from "next-auth";' : ""}

export async function ${method}${method === "GET" ? "(request: NextRequest)" : "(request: NextRequest)"} {
  try {
    ${route.auth_required ? `
    // 认证检查 / Auth check
    const session = await getServerSession();
    if (!session) {
      return NextResponse.json({ error: "Unauthorized" }, { status: 401 });
    }
    ` : ""}
    // 解析请求参数 / Parse request params
    ${paramsDestructure}
    ${paramsValidation}

    // TODO: 在此实现 Agent 处理逻辑 / Implement agent processing logic here
    // 调用 LLM 或执行工具 / Call LLM or execute tools

    return NextResponse.json({
      success: true,
      agent: "${agentName}",
      message: "处理完成",
      timestamp: new Date().toISOString(),
    });

  } catch (error) {
    console.error("[${agentName}] API Error:", error);
    return NextResponse.json(
      { error: "Internal server error", details: String(error) },
      { status: 500 }
    );
  }
}`;

  return { fileName, filePath, code, description: route.description };
}

/** 生成 React 组件代码 / Generate React component code */
export function generateComponent(comp: ComponentConfig, agentName: string): GeneratedComponent {
  const fileName = `${comp.name}.tsx`;
  const filePath = `src/components/${comp.name}.tsx`;

  const propsInterface = comp.props
    .map((p) => `  ${p}: string;`)
    .join("\n");

  const isClient = comp.type === "client";

  const code = `// ═════════════════════════════════════════════════════════════════
// ${comp.name} — ${comp.description || `${agentName} 专用组件`}
// Agent: ${agentName}
// Generated by OmniMind Nexus Creator
// ═════════════════════════════════════════════════════════════════
${isClient ? '"use client";\n' : ""}
import { motion } from "framer-motion";

interface ${comp.name}Props {
${propsInterface}
}

export default function ${comp.name}({ ${comp.props.join(", ")} }: ${comp.name}Props) {
  return (
    <motion.div
      initial={{ opacity: 0, y: 12 }}
      animate={{ opacity: 1, y: 0 }}
      transition={{ duration: 0.4 }}
      className="border-2 border-ink bg-white p-4"
    >
      <div className="flex items-center gap-2 mb-3">
        <span className="pixel-text text-[10px] tracking-[0.15em] text-ink/50 uppercase">
          {comp.name}
        </span>
      </div>
      <div className="space-y-2">
        ${comp.props.map((p) => `
        <div className="flex items-center gap-2">
          <span className="pixel-text text-[9px] text-ink/40 w-16">{p}:</span>
          <span className="pixel-text text-[11px] text-ink/80">{${p}}</span>
        </div>`).join("")}
      </div>
    </motion.div>
  );
}`;

  return { fileName, filePath, code, description: comp.description || `${comp.name} 组件` };
}

/** 从扩展配置生成完整的 Next.js 扩展包 / Generate complete Next.js extension package from extension config */
export function generateNextJsExtension(ext: ExtensionConfig, agentName: string): NextJsExtension {
  const routes = ext.api_routes.map((r) => generateAPIRoute(r, agentName));
  const components = ext.components.map((c) => generateComponent(c, agentName));

  const readme = `# ${agentName} — Next.js Extension

## API Routes
${routes.map((r) => `- **${r.filePath}** — ${r.description}`).join("\n")}

## Components
${components.map((c) => `- **${c.filePath}** — ${c.description}`).join("\n")}

## 使用方式 / Usage

### 安装依赖
\`\`\`bash
npm install
\`\`\`

### 导入组件
\`\`\`tsx
${components.map((c) => `import ${c.filePath.split("/").pop()?.replace(".tsx", "")} from "${c.filePath.replace("src/", "@/").replace(".tsx", "")}";`).join("\n")}
\`\`\`

### 调用 API
\`\`\`ts
${routes.map((r) => `// ${r.description}
const res = await fetch("${r.filePath.replace("src/app", "").replace("/route.ts", "")}", {
  method: "${r.filePath.includes("GET") ? "GET" : "POST"}",
  headers: { "Content-Type": "application/json" },
  body: JSON.stringify({ /* params */ }),
});`).join("\n\n")}
\`\`\`

---
Generated by OmniMind Nexus Creator
`;

  return { routes, components, readme };
}

/** 从完整的 Agent DSL 配置生成所有扩展代码 / Generate all extension code from full Agent DSL config */
export function generateFullExtension(config: AgentDSLConfig): NextJsExtension {
  const base = generateNextJsExtension(config.extension, config.name);

  // 添加事件中间件 / Add event middleware
  if (config.events && config.events.length > 0) {
    const eventMiddleware = generateEventMiddleware(config.events, config.name);
    base.routes.push(eventMiddleware);
  }

  // 添加管道路由 / Add pipeline routes
  if (config.pipelines && config.pipelines.length > 0) {
    for (const pipe of config.pipelines) {
      const pipeRoute = generatePipelineRoute(pipe, config.name);
      base.routes.push(pipeRoute);
    }
  }

  // 添加状态机钩子 / Add state machine hook
  if (config.state_machine) {
    const smHook = generateStateMachineHook(config.state_machine, config.name);
    base.components.push(smHook);
  }

  // 添加通信中间件 / Add communication middleware
  if (config.communication) {
    const commMiddleware = generateCommunicationMiddleware(config.communication, config.name);
    base.routes.push(commMiddleware);
  }

  return base;
}

/** 生成自定义功能的 Next.js 代码（自由形式）/ Generate custom Next.js code (free-form) */

// ── 扩展生成器：事件中间件、管道路由、状态机钩子、通信中间件 / Extended generators: event middleware, pipeline routes, state machine hooks, communication middleware ──

/** 生成事件中间件 / Generate event middleware */
function generateEventMiddleware(events: EventHook[], agentName: string): GeneratedRoute {
  const eventHandlers = events.map((ev) => {
    const conditionCheck = ev.condition ? `\n  if (!(${ev.condition})) return;` : "";
    const asyncExec = ev.async ? "  // 异步执行 / Async execution\n  setTimeout(() => {" : "  // 同步执行 / Sync execution";
    const asyncEnd = ev.async ? `\n  }, ${ev.priority * 10});` : "";

    return `  // ${ev.event} (priority=${ev.priority})
  on("${ev.event}", async (data: unknown) => {${conditionCheck}${asyncExec}
    console.log("[${agentName}] Event: ${ev.event}, Action: ${ev.action}");
    // TODO: 实现 ${ev.action} / Implement ${ev.action}
    await handleEvent("${ev.event}", "${ev.action}", data);
  });${asyncEnd}`;
  }).join("\n\n");

  const code = `// ═════════════════════════════════════════════════════════════════
// 事件中间件 / Event Middleware
// Agent: ${agentName}
// Generated by OmniMind Nexus Creator
// ═════════════════════════════════════════════════════════════════

import { NextRequest, NextResponse } from "next/server";

type EventName = ${events.map((e) => `"${e.event}"`).join(" | ")};
type EventHandler = (data: unknown) => Promise<void>;

const listeners: Map<EventName, EventHandler[]> = new Map();

export function on(event: EventName, handler: EventHandler) {
  if (!listeners.has(event)) listeners.set(event, []);
  listeners.get(event)!.push(handler);
}

export async function emit(event: EventName, data: unknown) {
  const handlers = listeners.get(event);
  if (!handlers) return;
  await Promise.all(handlers.map((h) => h(data)));
}

async function handleEvent(event: string, action: string, data: unknown) {
  console.log(\`[${agentName}] Handling \${event} -> \${action}\`, data);
  // TODO: 实现事件处理逻辑 / Implement event handling logic
}

// 注册事件处理器 / Register event handlers
${eventHandlers}

// Next.js 中间件 / Next.js middleware
export async function middleware(request: NextRequest) {
  const path = request.nextUrl.pathname;

  // 根据路径触发事件 / Trigger events based on path
  ${events.filter((e) => e.event === "message_received").length > 0 ? `
  if (path.startsWith("/api/chat")) {
    await emit("message_received", { path, method: request.method });
  }` : ""}

  return NextResponse.next();
}

export const config = {
  matcher: ["/api/:path*"],
};`;

  return { fileName: `${agentName.replace(/\s+/g, "_")}_events.ts`, filePath: `src/middleware/${agentName.replace(/\s+/g, "_")}_events.ts`, code, description: "事件生命周期中间件" };
}

/** 生成管道路由 / Generate pipeline route */
function generatePipelineRoute(pipeline: PipelineConfig, agentName: string): GeneratedRoute {
  const stepExecutions = pipeline.steps.map((step) => `
  // 步骤: ${step.name} / Step: ${step.name}
  try {
    await executeStep({
      name: "${step.name}",
      description: "${step.description}",
      agent: "${step.agent || "auto"}",
      tools: ${JSON.stringify(step.tools)},
      timeout: ${step.timeout_seconds * 1000},
      retry: ${step.retry_count},
      onFailure: "${step.on_failure}",
      dependsOn: ${JSON.stringify(step.depends_on)},
      condition: ${step.condition ? `"${step.condition}"` : "null"},
    });
  } catch (error) {
    console.error(\`[${agentName}] Step ${step.name} failed:\`, error);
    if ("${step.on_failure}" === "abort") throw error;
    if ("${step.on_failure}" === "retry") {
      for (let attempt = 0; attempt < ${step.retry_count}; attempt++) {
        try { await executeStep({ name: "${step.name}", retry: attempt }); break; }
        catch { console.log(\`Retry \${attempt + 1}/\${${step.retry_count}} for ${step.name}\`); }
      }
    }
    ${step.fallback_step ? `if ("${step.on_failure}" === "fallback") { await executeStep({ name: "${step.fallback_step}" }); }` : ""}
  }`).join("\n");

  const code = `// ═════════════════════════════════════════════════════════════════
// 管道路由: ${pipeline.name} / Pipeline Route: ${pipeline.name}
// Agent: ${agentName}
// Generated by OmniMind Nexus Creator
// ═════════════════════════════════════════════════════════════════

import { NextRequest, NextResponse } from "next/server";

interface StepConfig {
  name: string;
  description: string;
  agent: string;
  tools: string[];
  timeout: number;
  retry: number;
  onFailure: string;
  dependsOn: string[];
  condition: string | null;
}

async function executeStep(config: StepConfig): Promise<unknown> {
  // 检查依赖 / Check dependencies
  if (config.condition) {
    const shouldRun = evaluateCondition(config.condition);
    if (!shouldRun) {
      console.log(\`[${agentName}] Skipping step \${config.name} (condition not met)\`);
      return null;
    }
  }

  console.log(\`[${agentName}] Executing step: \${config.name}\`);
  // TODO: 实现步骤执行逻辑 / Implement step execution logic
  return { step: config.name, status: "completed" };
}

function evaluateCondition(condition: string): boolean {
  // TODO: 实现条件求值 / Implement condition evaluation
  return true;
}

export async function POST(request: NextRequest) {
  try {
    const body = await request.json();
    console.log(\`[${agentName}] Pipeline "${pipeline.name}" triggered\`, body);

    ${stepExecutions}

    // 完成处理 / Completion handling
    ${pipeline.on_complete ? `await executeStep({ name: "${pipeline.on_complete}", description: "完成处理", agent: "auto", tools: [], timeout: 30000, retry: 0, onFailure: "skip", dependsOn: [], condition: null });` : "// No completion action"}

    return NextResponse.json({
      success: true,
      pipeline: "${pipeline.name}",
      stepsCompleted: ${pipeline.steps.length},
      timestamp: new Date().toISOString(),
    });

  } catch (error) {
    console.error(\`[${agentName}] Pipeline "${pipeline.name}" failed:\`, error);
    return NextResponse.json(
      { error: "Pipeline execution failed", details: String(error) },
      { status: 500 }
    );
  }
}`;

  return {
    fileName: `${agentName.replace(/\s+/g, "_")}_${pipeline.name.replace(/\s+/g, "_")}_pipeline.ts`,
    filePath: `src/app/api/pipeline/${pipeline.name.replace(/\s+/g, "-").toLowerCase()}/route.ts`,
    code,
    description: `管道: ${pipeline.name} — ${pipeline.description}`,
  };
}

/** 生成状态机钩子 / Generate state machine hook */
function generateStateMachineHook(sm: StateMachineConfig, agentName: string): GeneratedComponent {
  const stateNames = sm.states.map((s) => `"${s.name}"`).join(" | ");

  const code = `// ═════════════════════════════════════════════════════════════════
// 状态机钩子: ${sm.name} / State Machine Hook: ${sm.name}
// Agent: ${agentName}
// Generated by OmniMind Nexus Creator
// ═════════════════════════════════════════════════════════════════

"use client";

import { useState, useCallback, useEffect } from "react";

type StateName = ${stateNames};

interface Transition {
  from: StateName;
  to: StateName;
  trigger: string;
  condition?: string;
  action?: string;
}

interface StateConfig {
  name: StateName;
  description: string;
  isInitial?: boolean;
  isFinal?: boolean;
  onEnter?: string;
  onExit?: string;
  timeout?: number;
}

const transitions: Transition[] = ${JSON.stringify(sm.transitions, null, 2)};

const states: StateConfig[] = ${JSON.stringify(sm.states, null, 2)};

export function use${toPascalCase(sm.name)}StateMachine() {
  const [currentState, setCurrentState] = useState<StateName>("${sm.initial}");
  const [history, setHistory] = useState<StateName[]>([]);

  const transition = useCallback((trigger: string) => {
    const validTransitions = transitions.filter(
      (t) => t.from === currentState && t.trigger === trigger
    );

    if (validTransitions.length === 0) {
      console.warn(\`[${agentName}] No transition from \${currentState} via \${trigger}\`);
      return false;
    }

    const t = validTransitions[0];
    if (t.condition) {
      // TODO: 条件求值 / Condition evaluation
      console.log(\`[${agentName}] Condition: \${t.condition}\`);
    }

    if (t.action) {
      console.log(\`[${agentName}] Action: \${t.action}\`);
    }

    setHistory((prev) => [...prev, currentState]);
    setCurrentState(t.to);
    return true;
  }, [currentState]);

  const currentStateConfig = states.find((s) => s.name === currentState);

  return {
    currentState,
    currentStateConfig,
    history,
    transition,
    canTransition: (trigger: string) =>
      transitions.some((t) => t.from === currentState && t.trigger === trigger),
    availableTransitions: transitions.filter((t) => t.from === currentState),
  };
}

function toPascalCase(str: string): string {
  return str.replace(/[^a-zA-Z0-9]/g, " ").split(" ").map((w) => w.charAt(0).toUpperCase() + w.slice(1).toLowerCase()).join("");
}`;

  return {
    fileName: `use${toPascalCase(sm.name)}StateMachine.ts`,
    filePath: `src/hooks/use${toPascalCase(sm.name)}StateMachine.ts`,
    code,
    description: `状态机钩子: ${sm.name}`,
  };
}

/** 生成通信中间件 / Generate communication middleware */
function generateCommunicationMiddleware(comm: CommunicationConfig, agentName: string): GeneratedRoute {
  const code = `// ═════════════════════════════════════════════════════════════════
// 通信中间件 / Communication Middleware
// Agent: ${agentName}
// Protocol: ${comm.protocol}, Encoding: ${comm.encoding}
// Generated by OmniMind Nexus Creator
// ═════════════════════════════════════════════════════════════════

import { NextRequest, NextResponse } from "next/server";

const COMM_CONFIG = {
  protocol: "${comm.protocol}",
  encoding: "${comm.encoding}",
  timeout: ${comm.timeout_ms},
  retryPolicy: "${comm.retry_policy}",
  maxRetries: ${comm.max_retries},
  heartbeat: ${comm.heartbeat_interval_ms},
  compression: "${comm.compression}",
  encryption: "${comm.encryption}",
  batchSize: ${comm.batch_size},
  queueCapacity: ${comm.queue_capacity},
};

// 消息队列 / Message queue
const messageQueue: Array<{ id: string; payload: unknown; timestamp: number }> = [];

// 心跳 / Heartbeat
let lastHeartbeat = Date.now();
setInterval(() => {
  lastHeartbeat = Date.now();
  console.log("[${agentName}] Heartbeat — protocol=${comm.protocol}");
}, ${comm.heartbeat_interval_ms});

// 批量发送 / Batch send
async function flushBatch() {
  if (messageQueue.length === 0) return;
  const batch = messageQueue.splice(0, ${comm.batch_size});
  console.log(\`[${agentName}] Flushing \${batch.length} messages via \${COMM_CONFIG.protocol}\`);
  // TODO: 实现批处理发送 / Implement batch send
}

setInterval(flushBatch, ${comm.timeout_ms});

// 消息入队 / Enqueue message
export function enqueue(payload: unknown): string {
  const id = crypto.randomUUID();
  messageQueue.push({ id, payload, timestamp: Date.now() });
  if (messageQueue.length >= ${comm.queue_capacity}) {
    console.warn(\`[${agentName}] Queue at capacity (\${messageQueue.length}/\${${comm.queue_capacity}})\`);
  }
  return id;
}

export async function middleware(request: NextRequest) {
  // 通信层处理 / Communication layer processing
  const startTime = Date.now();

  const response = NextResponse.next();

  // 添加通信头 / Add communication headers
  response.headers.set("X-Protocol", "${comm.protocol}");
  response.headers.set("X-Encoding", "${comm.encoding}");
  ${comm.compression !== "none" ? `response.headers.set("X-Compression", "${comm.compression}");` : ""}
  ${comm.encryption !== "none" ? `response.headers.set("X-Encryption", "${comm.encryption}");` : ""}

  const elapsed = Date.now() - startTime;
  if (elapsed > ${comm.timeout_ms}) {
    console.warn(\`[${agentName}] Request timeout: \${elapsed}ms > \${${comm.timeout_ms}}ms\`);
  }

  return response;
}

export const config = {
  matcher: ["/api/:path*"],
};`;

  return {
    fileName: `${agentName.replace(/\s+/g, "_")}_communication.ts`,
    filePath: `src/middleware/${agentName.replace(/\s+/g, "_")}_communication.ts`,
    code,
    description: `通信中间件: ${comm.protocol} / ${comm.encoding}`,
  };
}

function toPascalCase(str: string): string {
  return str.replace(/[^a-zA-Z0-9]/g, " ").split(" ").map((w) => w.charAt(0).toUpperCase() + w.slice(1).toLowerCase()).join("");
}

/** 生成自定义功能的 Next.js 代码（自由形式）/ Generate custom Next.js code (free-form) */
export function buildCustomNextJsCode(
  featureName: string,
  description: string,
  codeType: "api" | "component" | "page" | "layout" | "middleware",
  implementation: string,
): string {
  const header = `// ═════════════════════════════════════════════════════════════════
// ${featureName}
// ${description}
// Generated by OmniMind Nexus Creator
// ═════════════════════════════════════════════════════════════════
`;

  const boilerplate = getBoilerplate(codeType, featureName);

  return header + boilerplate.replace("// TODO: implementation", implementation);
}

/** 获取代码模板 / Get code boilerplate */
function getBoilerplate(type: string, name: string): string {
  switch (type) {
    case "api":
      return `
import { NextRequest, NextResponse } from "next/server";

export async function POST(request: NextRequest) {
  try {
    const body = await request.json();
    // TODO: implementation
    return NextResponse.json({ success: true });
  } catch (error) {
    return NextResponse.json({ error: String(error) }, { status: 500 });
  }
}
`;
    case "component":
      return `
"use client";

import { motion } from "framer-motion";

interface ${name}Props {
  data?: unknown;
}

export default function ${name}({ data }: ${name}Props) {
  return (
    <motion.div
      initial={{ opacity: 0 }}
      animate={{ opacity: 1 }}
      className="border-2 border-ink bg-white p-4"
    >
      // TODO: implementation
    </motion.div>
  );
}
`;
    case "page":
      return `
import { Metadata } from "next";

export const metadata: Metadata = {
  title: "${name}",
  description: "Generated by OmniMind Nexus Creator",
};

export default function ${name}Page() {
  return (
    <main className="min-h-screen bg-white p-8">
      // TODO: implementation
    </main>
  );
}
`;
    case "layout":
      return `
import { ReactNode } from "react";

export default function ${name}Layout({ children }: { children: ReactNode }) {
  return (
    <div className="min-h-screen bg-white">
      // TODO: implementation
      {children}
    </div>
  );
}
`;
    case "middleware":
      return `
import { NextRequest, NextResponse } from "next/server";

export function middleware(request: NextRequest) {
  // TODO: implementation
  return NextResponse.next();
}

export const config = {
  matcher: ["/api/:path*"],
};
`;
    default:
      return "// TODO: implementation";
  }
}