// ═══════════════════════════════════════════════════════════════════════
// Next.js 代码生成器 — 从 DSL 扩展配置生成 Next.js 代码
// Next.js Code Builder — generates Next.js code from DSL extension config
// ═══════════════════════════════════════════════════════════════════════

import type { APIRouteConfig, ComponentConfig, ExtensionConfig, AgentDSLConfig, EventHook, PipelineConfig, StateMachineConfig, CommunicationConfig, SwarmDSLConfig, EvolutionDSLConfig, KnowledgeGraphDSLConfig, MetacognitionDSLConfig } from "@/lib/agent-dsl";

/** 生成的 API 路由 / Generated API route */
export interface GeneratedRoute {
  fileName: string;
  filePath: string;
  code: string;
  description: string;
}

/** 生成的组件 / Generated component */
export interface GeneratedComponent {
  fileName: string;
  filePath: string;
  code: string;
  description: string;
}

/** 完整的 Next.js 扩展包 / Complete Next.js extension package */
export interface NextJsExtension {
  routes: GeneratedRoute[];
  components: GeneratedComponent[];
  readme: string;
}

/** 生成 API 路由代码 / Generate API route code */
export function generateAPIRoute(route: APIRouteConfig, agentName: string): GeneratedRoute {
  const method = route.method.toUpperCase();
  const routePath = route.path.startsWith("/") ? route.path : `/${route.path}`;
  const fileName = routePath.replace(/\//g, "_").replace(/^_/, "") + ".ts";
  const filePath = `src/app/api${routePath}/route.ts`;

  const paramsDestructure = route.params
    ? `const { ${Object.keys(route.params).join(", ")} } = await request.json();`
    : "";

  const paramsValidation = route.params
    ? Object.entries(route.params)
        .map(([k, v]) => `    if (!${k}) return NextResponse.json({ error: "${v} is required" }, { status: 400 });`)
        .join("\n")
    : "";

  const code = `// ═════════════════════════════════════════════════════════════════
// ${route.description}
// Agent: ${agentName}
// Generated by OmniMind Nexus Creator
// ═════════════════════════════════════════════════════════════════

import { NextRequest, NextResponse } from "next/server";
${route.auth_required ? 'import { getServerSession } from "next-auth";' : ""}

export async function ${method}${method === "GET" ? "(request: NextRequest)" : "(request: NextRequest)"} {
  try {
    ${route.auth_required ? `
    // 认证检查 / Auth check
    const session = await getServerSession();
    if (!session) {
      return NextResponse.json({ error: "Unauthorized" }, { status: 401 });
    }
    ` : ""}
    // 解析请求参数 / Parse request params
    ${paramsDestructure}
    ${paramsValidation}

    // TODO: 在此实现 Agent 处理逻辑 / Implement agent processing logic here
    // 调用 LLM 或执行工具 / Call LLM or execute tools

    return NextResponse.json({
      success: true,
      agent: "${agentName}",
      message: "处理完成",
      timestamp: new Date().toISOString(),
    });

  } catch (error) {
    console.error("[${agentName}] API Error:", error);
    return NextResponse.json(
      { error: "Internal server error", details: String(error) },
      { status: 500 }
    );
  }
}`;

  return { fileName, filePath, code, description: route.description };
}

/** 生成 React 组件代码 / Generate React component code */
export function generateComponent(comp: ComponentConfig, agentName: string): GeneratedComponent {
  const fileName = `${comp.name}.tsx`;
  const filePath = `src/components/${comp.name}.tsx`;

  const propsInterface = comp.props
    .map((p) => `  ${p}: string;`)
    .join("\n");

  const isClient = comp.type === "client";

  const code = `// ═════════════════════════════════════════════════════════════════
// ${comp.name} — ${comp.description || `${agentName} 专用组件`}
// Agent: ${agentName}
// Generated by OmniMind Nexus Creator
// ═════════════════════════════════════════════════════════════════
${isClient ? '"use client";\n' : ""}
import { motion } from "framer-motion";

interface ${comp.name}Props {
${propsInterface}
}

export default function ${comp.name}({ ${comp.props.join(", ")} }: ${comp.name}Props) {
  return (
    <motion.div
      initial={{ opacity: 0, y: 12 }}
      animate={{ opacity: 1, y: 0 }}
      transition={{ duration: 0.4 }}
      className="border-2 border-ink bg-white p-4"
    >
      <div className="flex items-center gap-2 mb-3">
        <span className="pixel-text text-[10px] tracking-[0.15em] text-ink/50 uppercase">
          {comp.name}
        </span>
      </div>
      <div className="space-y-2">
        ${comp.props.map((p) => `
        <div className="flex items-center gap-2">
          <span className="pixel-text text-[9px] text-ink/40 w-16">{p}:</span>
          <span className="pixel-text text-[11px] text-ink/80">{${p}}</span>
        </div>`).join("")}
      </div>
    </motion.div>
  );
}`;

  return { fileName, filePath, code, description: comp.description || `${comp.name} 组件` };
}

/** 从扩展配置生成完整的 Next.js 扩展包 / Generate complete Next.js extension package from extension config */
export function generateNextJsExtension(ext: ExtensionConfig, agentName: string): NextJsExtension {
  const routes = ext.api_routes.map((r) => generateAPIRoute(r, agentName));
  const components = ext.components.map((c) => generateComponent(c, agentName));

  const readme = `# ${agentName} — Next.js Extension

## API Routes
${routes.map((r) => `- **${r.filePath}** — ${r.description}`).join("\n")}

## Components
${components.map((c) => `- **${c.filePath}** — ${c.description}`).join("\n")}

## 使用方式 / Usage

### 安装依赖
\`\`\`bash
npm install
\`\`\`

### 导入组件
\`\`\`tsx
${components.map((c) => `import ${c.filePath.split("/").pop()?.replace(".tsx", "")} from "${c.filePath.replace("src/", "@/").replace(".tsx", "")}";`).join("\n")}
\`\`\`

### 调用 API
\`\`\`ts
${routes.map((r) => `// ${r.description}
const res = await fetch("${r.filePath.replace("src/app", "").replace("/route.ts", "")}", {
  method: "${r.filePath.includes("GET") ? "GET" : "POST"}",
  headers: { "Content-Type": "application/json" },
  body: JSON.stringify({ /* params */ }),
});`).join("\n\n")}
\`\`\`

---
Generated by OmniMind Nexus Creator
`;

  return { routes, components, readme };
}

/** 从完整的 Agent DSL 配置生成所有扩展代码 / Generate all extension code from full Agent DSL config */
export function generateFullExtension(config: AgentDSLConfig): NextJsExtension {
  const base = generateNextJsExtension(config.extension, config.name);

  // 添加事件中间件 / Add event middleware
  if (config.events && config.events.length > 0) {
    const eventMiddleware = generateEventMiddleware(config.events, config.name);
    base.routes.push(eventMiddleware);
  }

  // 添加管道路由 / Add pipeline routes
  if (config.pipelines && config.pipelines.length > 0) {
    for (const pipe of config.pipelines) {
      const pipeRoute = generatePipelineRoute(pipe, config.name);
      base.routes.push(pipeRoute);
    }
  }

  // 添加状态机钩子 / Add state machine hook
  if (config.state_machine) {
    const smHook = generateStateMachineHook(config.state_machine, config.name);
    base.components.push(smHook);
  }

  // 添加通信中间件 / Add communication middleware
  if (config.communication) {
    const commMiddleware = generateCommunicationMiddleware(config.communication, config.name);
    base.routes.push(commMiddleware);
  }

  // 添加蜂群智能路由 / Add swarm intelligence route
  if (config.swarm) {
    const swarmRoute = generateSwarmRoute(config.swarm, config.name);
    base.routes.push(swarmRoute);
  }

  // 添加进化引擎路由 / Add evolution engine route
  if (config.evolution) {
    const evolutionRoute = generateEvolutionRoute(config.evolution, config.name);
    base.routes.push(evolutionRoute);
  }

  // 添加知识图谱组件 / Add knowledge graph component
  if (config.knowledge_graph) {
    const kgComponent = generateKnowledgeGraphComponent(config.knowledge_graph, config.name);
    base.components.push(kgComponent);
  }

  // 添加元认知组件 / Add metacognition component
  if (config.metacognition) {
    const metaComponent = generateMetacognitionComponent(config.metacognition, config.name);
    base.components.push(metaComponent);
  }

  return base;
}

/** 生成自定义功能的 Next.js 代码（自由形式）/ Generate custom Next.js code (free-form) */

// ── 扩展生成器：事件中间件、管道路由、状态机钩子、通信中间件 / Extended generators: event middleware, pipeline routes, state machine hooks, communication middleware ──

/** 生成事件中间件 / Generate event middleware */
function generateEventMiddleware(events: EventHook[], agentName: string): GeneratedRoute {
  const eventHandlers = events.map((ev) => {
    const conditionCheck = ev.condition ? `\n  if (!(${ev.condition})) return;` : "";
    const asyncExec = ev.async ? "  // 异步执行 / Async execution\n  setTimeout(() => {" : "  // 同步执行 / Sync execution";
    const asyncEnd = ev.async ? `\n  }, ${ev.priority * 10});` : "";

    return `  // ${ev.event} (priority=${ev.priority})
  on("${ev.event}", async (data: unknown) => {${conditionCheck}${asyncExec}
    console.log("[${agentName}] Event: ${ev.event}, Action: ${ev.action}");
    // TODO: 实现 ${ev.action} / Implement ${ev.action}
    await handleEvent("${ev.event}", "${ev.action}", data);
  });${asyncEnd}`;
  }).join("\n\n");

  const code = `// ═════════════════════════════════════════════════════════════════
// 事件中间件 / Event Middleware
// Agent: ${agentName}
// Generated by OmniMind Nexus Creator
// ═════════════════════════════════════════════════════════════════

import { NextRequest, NextResponse } from "next/server";

type EventName = ${events.map((e) => `"${e.event}"`).join(" | ")};
type EventHandler = (data: unknown) => Promise<void>;

const listeners: Map<EventName, EventHandler[]> = new Map();

export function on(event: EventName, handler: EventHandler) {
  if (!listeners.has(event)) listeners.set(event, []);
  listeners.get(event)!.push(handler);
}

export async function emit(event: EventName, data: unknown) {
  const handlers = listeners.get(event);
  if (!handlers) return;
  await Promise.all(handlers.map((h) => h(data)));
}

async function handleEvent(event: string, action: string, data: unknown) {
  console.log(\`[${agentName}] Handling \${event} -> \${action}\`, data);
  // TODO: 实现事件处理逻辑 / Implement event handling logic
}

// 注册事件处理器 / Register event handlers
${eventHandlers}

// Next.js 中间件 / Next.js middleware
export async function middleware(request: NextRequest) {
  const path = request.nextUrl.pathname;

  // 根据路径触发事件 / Trigger events based on path
  ${events.filter((e) => e.event === "message_received").length > 0 ? `
  if (path.startsWith("/api/chat")) {
    await emit("message_received", { path, method: request.method });
  }` : ""}

  return NextResponse.next();
}

export const config = {
  matcher: ["/api/:path*"],
};`;

  return { fileName: `${agentName.replace(/\s+/g, "_")}_events.ts`, filePath: `src/middleware/${agentName.replace(/\s+/g, "_")}_events.ts`, code, description: "事件生命周期中间件" };
}

/** 生成管道路由 / Generate pipeline route */
function generatePipelineRoute(pipeline: PipelineConfig, agentName: string): GeneratedRoute {
  const stepExecutions = pipeline.steps.map((step) => `
  // 步骤: ${step.name} / Step: ${step.name}
  try {
    await executeStep({
      name: "${step.name}",
      description: "${step.description}",
      agent: "${step.agent || "auto"}",
      tools: ${JSON.stringify(step.tools)},
      timeout: ${step.timeout_seconds * 1000},
      retry: ${step.retry_count},
      onFailure: "${step.on_failure}",
      dependsOn: ${JSON.stringify(step.depends_on)},
      condition: ${step.condition ? `"${step.condition}"` : "null"},
    });
  } catch (error) {
    console.error(\`[${agentName}] Step ${step.name} failed:\`, error);
    if ("${step.on_failure}" === "abort") throw error;
    if ("${step.on_failure}" === "retry") {
      for (let attempt = 0; attempt < ${step.retry_count}; attempt++) {
        try { await executeStep({ name: "${step.name}", retry: attempt }); break; }
        catch { console.log(\`Retry \${attempt + 1}/\${${step.retry_count}} for ${step.name}\`); }
      }
    }
    ${step.fallback_step ? `if ("${step.on_failure}" === "fallback") { await executeStep({ name: "${step.fallback_step}" }); }` : ""}
  }`).join("\n");

  const code = `// ═════════════════════════════════════════════════════════════════
// 管道路由: ${pipeline.name} / Pipeline Route: ${pipeline.name}
// Agent: ${agentName}
// Generated by OmniMind Nexus Creator
// ═════════════════════════════════════════════════════════════════

import { NextRequest, NextResponse } from "next/server";

interface StepConfig {
  name: string;
  description: string;
  agent: string;
  tools: string[];
  timeout: number;
  retry: number;
  onFailure: string;
  dependsOn: string[];
  condition: string | null;
}

async function executeStep(config: StepConfig): Promise<unknown> {
  // 检查依赖 / Check dependencies
  if (config.condition) {
    const shouldRun = evaluateCondition(config.condition);
    if (!shouldRun) {
      console.log(\`[${agentName}] Skipping step \${config.name} (condition not met)\`);
      return null;
    }
  }

  console.log(\`[${agentName}] Executing step: \${config.name}\`);
  // TODO: 实现步骤执行逻辑 / Implement step execution logic
  return { step: config.name, status: "completed" };
}

function evaluateCondition(condition: string): boolean {
  // TODO: 实现条件求值 / Implement condition evaluation
  return true;
}

export async function POST(request: NextRequest) {
  try {
    const body = await request.json();
    console.log(\`[${agentName}] Pipeline "${pipeline.name}" triggered\`, body);

    ${stepExecutions}

    // 完成处理 / Completion handling
    ${pipeline.on_complete ? `await executeStep({ name: "${pipeline.on_complete}", description: "完成处理", agent: "auto", tools: [], timeout: 30000, retry: 0, onFailure: "skip", dependsOn: [], condition: null });` : "// No completion action"}

    return NextResponse.json({
      success: true,
      pipeline: "${pipeline.name}",
      stepsCompleted: ${pipeline.steps.length},
      timestamp: new Date().toISOString(),
    });

  } catch (error) {
    console.error(\`[${agentName}] Pipeline "${pipeline.name}" failed:\`, error);
    return NextResponse.json(
      { error: "Pipeline execution failed", details: String(error) },
      { status: 500 }
    );
  }
}`;

  return {
    fileName: `${agentName.replace(/\s+/g, "_")}_${pipeline.name.replace(/\s+/g, "_")}_pipeline.ts`,
    filePath: `src/app/api/pipeline/${pipeline.name.replace(/\s+/g, "-").toLowerCase()}/route.ts`,
    code,
    description: `管道: ${pipeline.name} — ${pipeline.description}`,
  };
}

/** 生成状态机钩子 / Generate state machine hook */
function generateStateMachineHook(sm: StateMachineConfig, agentName: string): GeneratedComponent {
  const stateNames = sm.states.map((s) => `"${s.name}"`).join(" | ");

  const code = `// ═════════════════════════════════════════════════════════════════
// 状态机钩子: ${sm.name} / State Machine Hook: ${sm.name}
// Agent: ${agentName}
// Generated by OmniMind Nexus Creator
// ═════════════════════════════════════════════════════════════════

"use client";

import { useState, useCallback, useEffect } from "react";

type StateName = ${stateNames};

interface Transition {
  from: StateName;
  to: StateName;
  trigger: string;
  condition?: string;
  action?: string;
}

interface StateConfig {
  name: StateName;
  description: string;
  isInitial?: boolean;
  isFinal?: boolean;
  onEnter?: string;
  onExit?: string;
  timeout?: number;
}

const transitions: Transition[] = ${JSON.stringify(sm.transitions, null, 2)};

const states: StateConfig[] = ${JSON.stringify(sm.states, null, 2)};

export function use${toPascalCase(sm.name)}StateMachine() {
  const [currentState, setCurrentState] = useState<StateName>("${sm.initial}");
  const [history, setHistory] = useState<StateName[]>([]);

  const transition = useCallback((trigger: string) => {
    const validTransitions = transitions.filter(
      (t) => t.from === currentState && t.trigger === trigger
    );

    if (validTransitions.length === 0) {
      console.warn(\`[${agentName}] No transition from \${currentState} via \${trigger}\`);
      return false;
    }

    const t = validTransitions[0];
    if (t.condition) {
      // TODO: 条件求值 / Condition evaluation
      console.log(\`[${agentName}] Condition: \${t.condition}\`);
    }

    if (t.action) {
      console.log(\`[${agentName}] Action: \${t.action}\`);
    }

    setHistory((prev) => [...prev, currentState]);
    setCurrentState(t.to);
    return true;
  }, [currentState]);

  const currentStateConfig = states.find((s) => s.name === currentState);

  return {
    currentState,
    currentStateConfig,
    history,
    transition,
    canTransition: (trigger: string) =>
      transitions.some((t) => t.from === currentState && t.trigger === trigger),
    availableTransitions: transitions.filter((t) => t.from === currentState),
  };
}

function toPascalCase(str: string): string {
  return str.replace(/[^a-zA-Z0-9]/g, " ").split(" ").map((w) => w.charAt(0).toUpperCase() + w.slice(1).toLowerCase()).join("");
}`;

  return {
    fileName: `use${toPascalCase(sm.name)}StateMachine.ts`,
    filePath: `src/hooks/use${toPascalCase(sm.name)}StateMachine.ts`,
    code,
    description: `状态机钩子: ${sm.name}`,
  };
}

/** 生成通信中间件 / Generate communication middleware */
function generateCommunicationMiddleware(comm: CommunicationConfig, agentName: string): GeneratedRoute {
  const code = `// ═════════════════════════════════════════════════════════════════
// 通信中间件 / Communication Middleware
// Agent: ${agentName}
// Protocol: ${comm.protocol}, Encoding: ${comm.encoding}
// Generated by OmniMind Nexus Creator
// ═════════════════════════════════════════════════════════════════

import { NextRequest, NextResponse } from "next/server";

const COMM_CONFIG = {
  protocol: "${comm.protocol}",
  encoding: "${comm.encoding}",
  timeout: ${comm.timeout_ms},
  retryPolicy: "${comm.retry_policy}",
  maxRetries: ${comm.max_retries},
  heartbeat: ${comm.heartbeat_interval_ms},
  compression: "${comm.compression}",
  encryption: "${comm.encryption}",
  batchSize: ${comm.batch_size},
  queueCapacity: ${comm.queue_capacity},
};

// 消息队列 / Message queue
const messageQueue: Array<{ id: string; payload: unknown; timestamp: number }> = [];

// 心跳 / Heartbeat
let lastHeartbeat = Date.now();
setInterval(() => {
  lastHeartbeat = Date.now();
  console.log("[${agentName}] Heartbeat — protocol=${comm.protocol}");
}, ${comm.heartbeat_interval_ms});

// 批量发送 / Batch send
async function flushBatch() {
  if (messageQueue.length === 0) return;
  const batch = messageQueue.splice(0, ${comm.batch_size});
  console.log(\`[${agentName}] Flushing \${batch.length} messages via \${COMM_CONFIG.protocol}\`);
  // TODO: 实现批处理发送 / Implement batch send
}

setInterval(flushBatch, ${comm.timeout_ms});

// 消息入队 / Enqueue message
export function enqueue(payload: unknown): string {
  const id = crypto.randomUUID();
  messageQueue.push({ id, payload, timestamp: Date.now() });
  if (messageQueue.length >= ${comm.queue_capacity}) {
    console.warn(\`[${agentName}] Queue at capacity (\${messageQueue.length}/\${${comm.queue_capacity}})\`);
  }
  return id;
}

export async function middleware(request: NextRequest) {
  // 通信层处理 / Communication layer processing
  const startTime = Date.now();

  const response = NextResponse.next();

  // 添加通信头 / Add communication headers
  response.headers.set("X-Protocol", "${comm.protocol}");
  response.headers.set("X-Encoding", "${comm.encoding}");
  ${comm.compression !== "none" ? `response.headers.set("X-Compression", "${comm.compression}");` : ""}
  ${comm.encryption !== "none" ? `response.headers.set("X-Encryption", "${comm.encryption}");` : ""}

  const elapsed = Date.now() - startTime;
  if (elapsed > ${comm.timeout_ms}) {
    console.warn(\`[${agentName}] Request timeout: \${elapsed}ms > \${${comm.timeout_ms}}ms\`);
  }

  return response;
}

export const config = {
  matcher: ["/api/:path*"],
};`;

  return {
    fileName: `${agentName.replace(/\s+/g, "_")}_communication.ts`,
    filePath: `src/middleware/${agentName.replace(/\s+/g, "_")}_communication.ts`,
    code,
    description: `通信中间件: ${comm.protocol} / ${comm.encoding}`,
  };
}

function toPascalCase(str: string): string {
  return str.replace(/[^a-zA-Z0-9]/g, " ").split(" ").map((w) => w.charAt(0).toUpperCase() + w.slice(1).toLowerCase()).join("");
}

// ── 创新功能生成器：蜂群、进化、知识图谱、元认知 / Novel feature generators: swarm, evolution, knowledge graph, metacognition ──

/** 生成蜂群智能路由 / Generate swarm intelligence route */
function generateSwarmRoute(swarm: SwarmDSLConfig, agentName: string): GeneratedRoute {
  const code = `// ═════════════════════════════════════════════════════════════════
// 蜂群智能路由 / Swarm Intelligence Route
// Agent: ${agentName}
// Generated by OmniMind Nexus Creator
// ═════════════════════════════════════════════════════════════════

import { NextRequest, NextResponse } from "next/server";
import { runSwarmConsensus, type SwarmConfig } from "@/lib/swarm";

const SWARM_CONFIG: SwarmConfig = {
  populationSize: ${swarm.population_size},
  maxIterations: ${swarm.max_iterations},
  convergenceThreshold: ${swarm.convergence_threshold},
  explorationRatio: ${swarm.exploration_ratio},
  pheromoneWeight: ${swarm.pheromone_weight},
  socialWeight: ${swarm.social_weight},
  cognitiveWeight: ${swarm.cognitive_weight},
  inertiaWeight: ${swarm.inertia_weight},
  dimensions: ${swarm.dimensions},
  bounds: [${swarm.bounds[0]}, ${swarm.bounds[1]}],
};

export async function POST(request: NextRequest) {
  try {
    const body = await request.json();
    const { agentNames, fitnessData } = body;

    if (!agentNames || !Array.isArray(agentNames)) {
      return NextResponse.json({ error: "agentNames array is required" }, { status: 400 });
    }

    // 适应度函数 / Fitness function
    const fitnessFn = (position: number[]): number => {
      // 基于用户提供的 fitnessData 评估 / Evaluate based on user-provided fitnessData
      if (fitnessData?.weights) {
        return position.reduce((sum, p, i) => sum + p * (fitnessData.weights[i] || 1), 0);
      }
      return position.reduce((sum, p) => sum + p, 0) / position.length;
    };

    const result = runSwarmConsensus(SWARM_CONFIG, agentNames, fitnessFn);

    return NextResponse.json({
      success: true,
      consensus: {
        solution: result.solution,
        quality: result.quality,
        agreement: result.agreement,
        iterations: result.iterations,
        convergenceTime: result.convergenceTime,
        participants: result.participants,
      },
      minorityReports: result.minorityReports,
      ${swarm.waggle_dance ? "danceHistory: result.danceHistory," : ""}
    });
  } catch (error) {
    return NextResponse.json({ error: String(error) }, { status: 500 });
  }
}`;

  return {
    fileName: `${agentName.replace(/\s+/g, "_")}_swarm.ts`,
    filePath: `src/app/api/swarm/${agentName.replace(/\s+/g, "-").toLowerCase()}/route.ts`,
    code,
    description: `蜂群智能: ${agentName} — 共识决策引擎`,
  };
}

/** 生成进化引擎路由 / Generate evolution engine route */
function generateEvolutionRoute(evol: EvolutionDSLConfig, agentName: string): GeneratedRoute {
  const code = `// ═════════════════════════════════════════════════════════════════
// 进化引擎路由 / Evolution Engine Route
// Agent: ${agentName}
// Generated by OmniMind Nexus Creator
// ═════════════════════════════════════════════════════════════════

import { NextRequest, NextResponse } from "next/server";
import { runEvolution, type EvolutionConfig, type Chromosome } from "@/lib/evolution";

const EVOLUTION_CONFIG: EvolutionConfig = {
  populationSize: ${evol.population_size},
  eliteCount: ${evol.elite_count},
  crossoverRate: ${evol.crossover_rate},
  mutationRate: ${evol.mutation_rate},
  tournamentSize: ${evol.tournament_size},
  maxGenerations: ${evol.max_generations},
  targetFitness: ${evol.target_fitness},
  stagnationLimit: ${evol.stagnation_limit},
};

export async function POST(request: NextRequest) {
  try {
    const body = await request.json();
    const { fitnessData } = body;

    // 适应度函数 / Fitness function
    const fitnessFn = async (chromosome: Chromosome): Promise<number> => {
      // 基于用户提供的评估数据 / Evaluate based on user-provided data
      if (fitnessData?.scores) {
        const geneValues = chromosome.genes.map((g) => g.value);
        return geneValues.reduce((sum, v, i) => sum + v * (fitnessData.scores[i] || 1), 0) / geneValues.length;
      }
      // 默认：随机评估 / Default: random evaluation
      return Math.random();
    };

    const result = await runEvolution(EVOLUTION_CONFIG, fitnessFn);

    if (result.bestChromosome) {
      const bestGenes = result.bestChromosome.genes.map((g) => ({
        name: g.name,
        value: g.value,
        min: g.min,
        max: g.max,
      }));

      return NextResponse.json({
        success: true,
        bestChromosome: {
          id: result.bestChromosome.id,
          fitness: result.bestChromosome.fitness,
          generation: result.bestChromosome.generation,
          mutationCount: result.bestChromosome.mutationCount,
          genes: bestGenes,
        },
        totalGenerations: result.totalGenerations,
        totalTime: result.totalTime,
        convergenceReason: result.convergenceReason,
        history: result.history.map((h) => ({
          generation: h.generation,
          bestFitness: h.bestFitness,
          avgFitness: h.avgFitness,
          diversity: h.diversity,
        })),
      });
    }

    return NextResponse.json({ error: "Evolution failed to produce results" }, { status: 500 });
  } catch (error) {
    return NextResponse.json({ error: String(error) }, { status: 500 });
  }
}`;

  return {
    fileName: `${agentName.replace(/\s+/g, "_")}_evolution.ts`,
    filePath: `src/app/api/evolution/${agentName.replace(/\s+/g, "-").toLowerCase()}/route.ts`,
    code,
    description: `进化引擎: ${agentName} — 遗传算法参数调优`,
  };
}

/** 生成知识图谱可视化组件 / Generate knowledge graph visualization component */
function generateKnowledgeGraphComponent(kg: KnowledgeGraphDSLConfig, agentName: string): GeneratedComponent {
  const code = `// ═════════════════════════════════════════════════════════════════
// 知识图谱可视化组件 / Knowledge Graph Visualization Component
// Agent: ${agentName}
// Generated by OmniMind Nexus Creator
// ═════════════════════════════════════════════════════════════════

"use client";

import { useState, useMemo } from "react";
import { motion, AnimatePresence } from "framer-motion";

interface GraphEntity {
  id: string;
  name: string;
  type: string;
  confidence: number;
  accessCount: number;
  tags: string[];
}

interface GraphRelation {
  id: string;
  from: string;
  to: string;
  type: string;
  weight: number;
}

interface KnowledgeGraphProps {
  entities: GraphEntity[];
  relations: GraphRelation[];
  onEntityClick?: (entity: GraphEntity) => void;
}

const TYPE_COLORS: Record<string, string> = {
  concept: "#3B82F6",
  person: "#10B981",
  tool: "#F59E0B",
  file: "#8B5CF6",
  decision: "#EF4444",
  error: "#DC2626",
  pattern: "#06B6D4",
};

const RELATION_COLORS: Record<string, string> = {
  depends_on: "#F59E0B",
  produces: "#10B981",
  contradicts: "#EF4444",
  supports: "#3B82F6",
  extends: "#8B5CF6",
  replaces: "#DC2626",
  relates_to: "#6B7280",
};

export default function ${toPascalCase(agentName)}KnowledgeGraph({
  entities,
  relations,
  onEntityClick,
}: KnowledgeGraphProps) {
  const [selectedEntity, setSelectedEntity] = useState<GraphEntity | null>(null);
  const [filter, setFilter] = useState<string>("all");

  const filteredEntities = useMemo(() => {
    if (filter === "all") return entities;
    return entities.filter((e) => e.type === filter);
  }, [entities, filter]);

  const connectedRelations = useMemo(() => {
    if (!selectedEntity) return [];
    return relations.filter(
      (r) => r.from === selectedEntity.id || r.to === selectedEntity.id
    );
  }, [relations, selectedEntity]);

  const entityTypes = useMemo(() => {
    const types = new Set(entities.map((e) => e.type));
    return Array.from(types);
  }, [entities]);

  return (
    <div className="border-2 border-ink bg-white">
      {/* 头部 / Header */}
      <div className="border-b-2 border-ink px-4 py-3 flex items-center justify-between">
        <div className="flex items-center gap-2">
          <span className="pixel-text text-[10px] tracking-[0.15em] text-ink/50 uppercase">
            Knowledge Graph
          </span>
          <span className="text-[9px] text-ink/30">
            {entities.length} entities · {relations.length} relations
          </span>
        </div>
        <div className="flex gap-1">
          <button
            onClick={() => setFilter("all")}
            className={\`pixel-text text-[9px] px-2 py-1 border border-ink/20 \${
              filter === "all" ? "bg-ink text-white" : "bg-white text-ink/60 hover:bg-ink/5"
            }\`}
          >
            All
          </button>
          {entityTypes.map((type) => (
            <button
              key={type}
              onClick={() => setFilter(type)}
              className={\`pixel-text text-[9px] px-2 py-1 border border-ink/20 \${
                filter === type ? "bg-ink text-white" : "bg-white text-ink/60 hover:bg-ink/5"
              }\`}
            >
              {type}
            </button>
          ))}
        </div>
      </div>

      {/* 图谱主体 / Graph body */}
      <div className="p-4">
        <div className="grid grid-cols-3 gap-2">
          <AnimatePresence>
            {filteredEntities.map((entity) => {
              const color = TYPE_COLORS[entity.type] || "#6B7280";
              const isSelected = selectedEntity?.id === entity.id;
              const connectionCount = relations.filter(
                (r) => r.from === entity.id || r.to === entity.id
              ).length;

              return (
                <motion.button
                  key={entity.id}
                  layout
                  initial={{ opacity: 0, scale: 0.9 }}
                  animate={{ opacity: 1, scale: 1 }}
                  exit={{ opacity: 0, scale: 0.9 }}
                  onClick={() => {
                    setSelectedEntity(isSelected ? null : entity);
                    onEntityClick?.(entity);
                  }}
                  className={\`text-left border-2 p-3 transition-colors \${
                    isSelected ? "border-ink bg-ink/5" : "border-ink/20 hover:border-ink/40"
                  }\`}
                  style={{ borderLeftColor: color }}
                >
                  <div className="flex items-center justify-between mb-1">
                    <span className="pixel-text text-[10px] text-ink/80 font-medium truncate">
                      {entity.name}
                    </span>
                    <span className="text-[8px] text-ink/30">{connectionCount}</span>
                  </div>
                  <div className="flex items-center gap-2">
                    <span
                      className="text-[8px] px-1.5 py-0.5 border"
                      style={{ borderColor: color, color }}
                    >
                      {entity.type}
                    </span>
                    <span className="text-[8px] text-ink/30">
                      {Math.round(entity.confidence * 100)}%
                    </span>
                  </div>
                  {entity.tags.length > 0 && (
                    <div className="flex gap-1 mt-1.5 flex-wrap">
                      {entity.tags.slice(0, 3).map((tag) => (
                        <span key={tag} className="text-[7px] text-ink/40 bg-ink/5 px-1">
                          {tag}
                        </span>
                      ))}
                    </div>
                  )}
                </motion.button>
              );
            })}
          </AnimatePresence>
        </div>

        {/* 选中实体的关系 / Selected entity relations */}
        {selectedEntity && connectedRelations.length > 0 && (
          <motion.div
            initial={{ height: 0, opacity: 0 }}
            animate={{ height: "auto", opacity: 1 }}
            className="border-t-2 border-ink/20 mt-3 pt-3"
          >
            <span className="pixel-text text-[9px] text-ink/40 uppercase">
              Relations ({connectedRelations.length})
            </span>
            <div className="mt-2 space-y-1">
              {connectedRelations.map((rel) => {
                const targetId = rel.from === selectedEntity.id ? rel.to : rel.from;
                const target = entities.find((e) => e.id === targetId);
                const color = RELATION_COLORS[rel.type] || "#6B7280";
                const direction = rel.from === selectedEntity.id ? "→" : "←";

                return (
                  <div
                    key={rel.id}
                    className="flex items-center gap-2 text-[9px] py-1 px-2 border border-ink/10"
                  >
                    <span className="text-ink/60">{selectedEntity.name}</span>
                    <span style={{ color }}>{direction} {rel.type}</span>
                    <span className="text-ink/80 font-medium">
                      {target?.name || targetId}
                    </span>
                    <span className="ml-auto text-ink/30">
                      {rel.weight > 0 ? "+" : ""}{rel.weight.toFixed(1)}
                    </span>
                  </div>
                );
              })}
            </div>
          </motion.div>
        )}
      </div>
    </div>
  );
}`;

  return {
    fileName: `${toPascalCase(agentName)}KnowledgeGraph.tsx`,
    filePath: `src/components/${toPascalCase(agentName)}KnowledgeGraph.tsx`,
    code,
    description: `知识图谱: ${agentName} — 语义网络可视化`,
  };
}

/** 生成元认知仪表盘组件 / Generate metacognition dashboard component */
function generateMetacognitionComponent(meta: MetacognitionDSLConfig, agentName: string): GeneratedComponent {
  const code = `// ═════════════════════════════════════════════════════════════════
// 元认知仪表盘 / Metacognition Dashboard
// Agent: ${agentName}
// Generated by OmniMind Nexus Creator
// ═════════════════════════════════════════════════════════════════

"use client";

import { useState, useMemo } from "react";
import { motion } from "framer-motion";

interface ThinkingStep {
  id: string;
  stepNumber: number;
  type: string;
  content: string;
  confidence: number;
  biases: string[];
  assumptions: string[];
  evidence: string[];
}

interface ReflectionReport {
  id: string;
  overallScore: number;
  strengths: string[];
  weaknesses: string[];
  detectedBiases: Array<{
    bias: string;
    severity: number;
    evidence: string;
    suggestion: string;
  }>;
  blindSpots: string[];
  improvementPlan: string[];
  alternativePaths: string[];
}

interface MetacognitionDashboardProps {
  thinkingChain?: {
    steps: ThinkingStep[];
    totalDuration: number;
    selfRating: number;
  };
  reflectionReport?: ReflectionReport;
  calibrationStats?: {
    accuracy: number;
    avgConfidence: number;
    calibrationError: number;
    isOverconfident: boolean;
    isUnderconfident: boolean;
  };
}

const STEP_TYPE_LABELS: Record<string, string> = {
  observation: "Observe",
  hypothesis: "Hypothesize",
  analysis: "Analyze",
  evaluation: "Evaluate",
  conclusion: "Conclude",
  question: "Question",
  assumption: "Assume",
  revision: "Revise",
};

export default function ${toPascalCase(agentName)}Metacognition({
  thinkingChain,
  reflectionReport,
  calibrationStats,
}: MetacognitionDashboardProps) {
  const [activeTab, setActiveTab] = useState<"chain" | "calibration" | "reflection">("chain");

  const stepTypeCounts = useMemo(() => {
    if (!thinkingChain?.steps) return {};
    return thinkingChain.steps.reduce((acc, s) => {
      acc[s.type] = (acc[s.type] || 0) + 1;
      return acc;
    }, {} as Record<string, number>);
  }, [thinkingChain]);

  return (
    <div className="border-2 border-ink bg-white">
      {/* 头部 / Header */}
      <div className="border-b-2 border-ink px-4 py-3 flex items-center justify-between">
        <span className="pixel-text text-[10px] tracking-[0.15em] text-ink/50 uppercase">
          Metacognition
        </span>
        {reflectionReport && (
          <span className={\`pixel-text text-[9px] px-2 py-0.5 \${
            reflectionReport.overallScore >= 0.7
              ? "bg-green-100 text-green-700"
              : reflectionReport.overallScore >= 0.4
              ? "bg-yellow-100 text-yellow-700"
              : "bg-red-100 text-red-700"
          }\`}>
            Score: {Math.round(reflectionReport.overallScore * 100)}
          </span>
        )}
      </div>

      {/* Tab 切换 / Tab switcher */}
      <div className="flex border-b border-ink/20">
        {(["chain", "calibration", "reflection"] as const).map((tab) => (
          <button
            key={tab}
            onClick={() => setActiveTab(tab)}
            className={\`pixel-text text-[9px] px-4 py-2 transition-colors \${
              activeTab === tab
                ? "border-b-2 border-ink text-ink font-medium"
                : "text-ink/40 hover:text-ink/60"
            }\`}
          >
            {tab === "chain" ? "Thinking Chain" : tab === "calibration" ? "Calibration" : "Reflection"}
          </button>
        ))}
      </div>

      {/* 思维链 / Thinking Chain */}
      {activeTab === "chain" && thinkingChain && (
        <div className="p-4 space-y-2 max-h-96 overflow-y-auto">
          {thinkingChain.steps.map((step) => (
            <motion.div
              key={step.id}
              initial={{ opacity: 0, x: -8 }}
              animate={{ opacity: 1, x: 0 }}
              className="border border-ink/15 p-3"
            >
              <div className="flex items-center justify-between mb-1">
                <div className="flex items-center gap-2">
                  <span className="text-[9px] text-ink/30 font-mono">
                    #{step.stepNumber}
                  </span>
                  <span className="text-[9px] text-ink/50 uppercase">
                    {STEP_TYPE_LABELS[step.type] || step.type}
                  </span>
                  {step.biases.length > 0 && (
                    <span className="text-[8px] text-red-500 bg-red-50 px-1">
                      {step.biases.length} bias
                    </span>
                  )}
                </div>
                <span className="text-[8px] text-ink/30">
                  {Math.round(step.confidence * 100)}%
                </span>
              </div>
              <p className="text-[10px] text-ink/70 leading-relaxed">
                {step.content.slice(0, 200)}
              </p>
              {step.evidence.length > 0 && (
                <div className="mt-1.5 flex gap-1 flex-wrap">
                  {step.evidence.map((e, i) => (
                    <span key={i} className="text-[7px] text-green-600 bg-green-50 px-1">
                      {e}
                    </span>
                  ))}
                </div>
              )}
            </motion.div>
          ))}
        </div>
      )}

      {/* 置信度校准 / Calibration */}
      {activeTab === "calibration" && calibrationStats && (
        <div className="p-4 space-y-3">
          <div className="grid grid-cols-3 gap-2">
            <div className="border border-ink/20 p-3 text-center">
              <div className="text-[8px] text-ink/40 uppercase">Accuracy</div>
              <div className="text-sm font-mono text-ink mt-1">
                {(calibrationStats.accuracy * 100).toFixed(1)}%
              </div>
            </div>
            <div className="border border-ink/20 p-3 text-center">
              <div className="text-[8px] text-ink/40 uppercase">Avg Confidence</div>
              <div className="text-sm font-mono text-ink mt-1">
                {(calibrationStats.avgConfidence * 100).toFixed(1)}%
              </div>
            </div>
            <div className="border border-ink/20 p-3 text-center">
              <div className="text-[8px] text-ink/40 uppercase">Error</div>
              <div className="text-sm font-mono mt-1" style={{
                color: calibrationStats.calibrationError < 0.1 ? "#10B981" : "#EF4444",
              }}>
                {(calibrationStats.calibrationError * 100).toFixed(1)}%
              </div>
            </div>
          </div>
          <div className="border border-ink/20 p-3">
            <span className="text-[8px] text-ink/40 uppercase block mb-1">Status</span>
            <span className={\`text-[10px] \${
              calibrationStats.isOverconfident
                ? "text-red-600"
                : calibrationStats.isUnderconfident
                ? "text-yellow-600"
                : "text-green-600"
            }\`}>
              {calibrationStats.isOverconfident
                ? "Overconfident — reduce confidence estimates"
                : calibrationStats.isUnderconfident
                ? "Underconfident — trust your judgment more"
                : "Well calibrated"}
            </span>
          </div>
        </div>
      )}

      {/* 反思报告 / Reflection */}
      {activeTab === "reflection" && reflectionReport && (
        <div className="p-4 space-y-3 max-h-96 overflow-y-auto">
          {reflectionReport.strengths.length > 0 && (
            <div>
              <span className="text-[8px] text-ink/40 uppercase">Strengths</span>
              <div className="mt-1 space-y-1">
                {reflectionReport.strengths.map((s, i) => (
                  <div key={i} className="text-[10px] text-green-700 bg-green-50 px-2 py-1 border border-green-200">
                    {s}
                  </div>
                ))}
              </div>
            </div>
          )}
          {reflectionReport.weaknesses.length > 0 && (
            <div>
              <span className="text-[8px] text-ink/40 uppercase">Weaknesses</span>
              <div className="mt-1 space-y-1">
                {reflectionReport.weaknesses.map((w, i) => (
                  <div key={i} className="text-[10px] text-red-700 bg-red-50 px-2 py-1 border border-red-200">
                    {w}
                  </div>
                ))}
              </div>
            </div>
          )}
          {reflectionReport.detectedBiases.length > 0 && (
            <div>
              <span className="text-[8px] text-ink/40 uppercase">Detected Biases</span>
              <div className="mt-1 space-y-2">
                {reflectionReport.detectedBiases.map((b, i) => (
                  <div key={i} className="border border-orange-200 bg-orange-50 p-2">
                    <div className="flex items-center justify-between">
                      <span className="text-[9px] font-medium text-orange-800">{b.bias}</span>
                      <span className="text-[8px] text-orange-500">{(b.severity * 100).toFixed(0)}%</span>
                    </div>
                    <p className="text-[8px] text-orange-600 mt-1">{b.evidence}</p>
                    <p className="text-[9px] text-orange-700 mt-1">{b.suggestion}</p>
                  </div>
                ))}
              </div>
            </div>
          )}
          {reflectionReport.improvementPlan.length > 0 && (
            <div>
              <span className="text-[8px] text-ink/40 uppercase">Improvement Plan</span>
              <div className="mt-1 space-y-1">
                {reflectionReport.improvementPlan.map((p, i) => (
                  <div key={i} className="text-[10px] text-blue-700 bg-blue-50 px-2 py-1 border border-blue-200">
                    {i + 1}. {p}
                  </div>
                ))}
              </div>
            </div>
          )}
        </div>
      )}

      {/* 空状态 / Empty state */}
      {activeTab === "chain" && !thinkingChain && (
        <div className="p-8 text-center text-[10px] text-ink/30">
          No thinking chain data available
        </div>
      )}
      {activeTab === "calibration" && !calibrationStats && (
        <div className="p-8 text-center text-[10px] text-ink/30">
          No calibration data available
        </div>
      )}
      {activeTab === "reflection" && !reflectionReport && (
        <div className="p-8 text-center text-[10px] text-ink/30">
          No reflection report available
        </div>
      )}
    </div>
  );
}`;

  return {
    fileName: `${toPascalCase(agentName)}Metacognition.tsx`,
    filePath: `src/components/${toPascalCase(agentName)}Metacognition.tsx`,
    code,
    description: `元认知仪表盘: ${agentName} — 思维链可视化 + 置信度校准`,
  };
}

/** 生成自定义功能的 Next.js 代码（自由形式）/ Generate custom Next.js code (free-form) */
export function buildCustomNextJsCode(
  featureName: string,
  description: string,
  codeType: "api" | "component" | "page" | "layout" | "middleware",
  implementation: string,
): string {
  const header = `// ═════════════════════════════════════════════════════════════════
// ${featureName}
// ${description}
// Generated by OmniMind Nexus Creator
// ═════════════════════════════════════════════════════════════════
`;

  const boilerplate = getBoilerplate(codeType, featureName);

  return header + boilerplate.replace("// TODO: implementation", implementation);
}

/** 获取代码模板 / Get code boilerplate */
function getBoilerplate(type: string, name: string): string {
  switch (type) {
    case "api":
      return `
import { NextRequest, NextResponse } from "next/server";

export async function POST(request: NextRequest) {
  try {
    const body = await request.json();
    // TODO: implementation
    return NextResponse.json({ success: true });
  } catch (error) {
    return NextResponse.json({ error: String(error) }, { status: 500 });
  }
}
`;
    case "component":
      return `
"use client";

import { motion } from "framer-motion";

interface ${name}Props {
  data?: unknown;
}

export default function ${name}({ data }: ${name}Props) {
  return (
    <motion.div
      initial={{ opacity: 0 }}
      animate={{ opacity: 1 }}
      className="border-2 border-ink bg-white p-4"
    >
      // TODO: implementation
    </motion.div>
  );
}
`;
    case "page":
      return `
import { Metadata } from "next";

export const metadata: Metadata = {
  title: "${name}",
  description: "Generated by OmniMind Nexus Creator",
};

export default function ${name}Page() {
  return (
    <main className="min-h-screen bg-white p-8">
      // TODO: implementation
    </main>
  );
}
`;
    case "layout":
      return `
import { ReactNode } from "react";

export default function ${name}Layout({ children }: { children: ReactNode }) {
  return (
    <div className="min-h-screen bg-white">
      // TODO: implementation
      {children}
    </div>
  );
}
`;
    case "middleware":
      return `
import { NextRequest, NextResponse } from "next/server";

export function middleware(request: NextRequest) {
  // TODO: implementation
  return NextResponse.next();
}

export const config = {
  matcher: ["/api/:path*"],
};
`;
    default:
      return "// TODO: implementation";
  }
}